-- ==========================================
-- SYSTEM OF BADGES AND ACHIEVEMENTS
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Create user_badges Table
create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_key text not null,
  unlocked_at timestamptz not null default now(),
  is_viewed boolean not null default false
);

-- Ensure user can only earn each badge once
create unique index if not exists user_badges_user_badge_unique on public.user_badges (user_id, badge_key);

-- Add time_taken column to trivia_answers if it doesn't exist to track speed
alter table public.trivia_answers add column if not exists time_taken int;

-- Enable Row Level Security
alter table public.user_badges enable row level security;

-- RLS Policies
drop policy if exists user_badges_select_own on public.user_badges;
create policy user_badges_select_own on public.user_badges
  for select
  using (auth.uid() = user_id);

drop policy if exists user_badges_update_own on public.user_badges;
create policy user_badges_update_own on public.user_badges
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Expose to Supabase Realtime
alter publication supabase_realtime add table public.user_badges;

-- 2. Badge Award Helper Function
create or replace function public.award_badge(target_user_id uuid, target_badge_key text)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.user_badges (user_id, badge_key)
  values (target_user_id, target_badge_key)
  on conflict (user_id, badge_key) do nothing;
end;
$$;

-- 3. Predictions Trigger Function
create or replace function public.trigger_check_prediction_badges()
returns trigger
language plpgsql
security definer
as $$
declare
  uid uuid;
  total_preds int;
  exact_preds int;
  exact_draw_preds int;
  exact_high_scorer int;
  consec_exact int;
  first_kickoff timestamptz;
  has_first_pts boolean;
  total_pts int;
  pred_points_50 boolean;
  pred_points_100 boolean;
  pred_points_200 boolean;
  group_stage_count int;
  knockout_stage_count int;
  invicto_days_count int;
  group_a_correct_count int;
  comeback_king_count int;
  m_home_score int;
  m_away_score int;
  is_exact_hit boolean;
begin
  -- Triggered on updates or inserts to predictions
  uid := NEW.user_id;

  -- 1. first_prediction
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_prediction') then
    perform public.award_badge(uid, 'first_prediction');
  end if;

  -- 2. ultimo_minuto (prediction placed between 10 and 5 minutes before kickoff)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'ultimo_minuto') then
    select match_date into first_kickoff from public.matches where id = NEW.match_id;
    if first_kickoff is not null and NEW.created_at >= first_kickoff - interval '10 minutes' and NEW.created_at < first_kickoff - interval '5 minutes' then
      perform public.award_badge(uid, 'ultimo_minuto');
    end if;
  end if;

  -- 3. half_predictions (52+ predictions)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'half_predictions') then
    select count(*) into total_preds from public.predictions where user_id = uid;
    if total_preds >= 52 then
      perform public.award_badge(uid, 'half_predictions');
    end if;
  end if;

  -- 4. all_predictions (104 predictions)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'all_predictions') then
    select count(*) into total_preds from public.predictions where user_id = uid;
    if total_preds >= 104 then
      perform public.award_badge(uid, 'all_predictions');
    end if;
  end if;

  -- 5. group_stage_complete (predicted all matches 1 to 72)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'group_stage_complete') then
    select count(*) into group_stage_count from public.predictions where user_id = uid and match_id <= 72;
    if group_stage_count = 72 then
      perform public.award_badge(uid, 'group_stage_complete');
    end if;
  end if;

  -- 6. knockout_stage_complete (predicted all matches 73 to 104)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'knockout_stage_complete') then
    select count(*) into knockout_stage_count from public.predictions where user_id = uid and match_id >= 73;
    if knockout_stage_count = 32 then
      perform public.award_badge(uid, 'knockout_stage_complete');
    end if;
  end if;

  -- Performance check: Stop if the prediction points are not resolved yet (e.g. match is pending)
  if NEW.points = 0 then
    return NEW;
  end if;

  -- Get official match score to check if it was an exact score prediction
  select home_score, away_score into m_home_score, m_away_score
  from public.matches
  where id = NEW.match_id;

  is_exact_hit := (m_home_score is not null and m_away_score is not null
                   and NEW.predicted_home = m_home_score
                   and NEW.predicted_away = m_away_score);

  -- 7. first_points (user earned points)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_points') then
    perform public.award_badge(uid, 'first_points');
  end if;

  -- 8. perfect_match (exact score hit)
  if is_exact_hit then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'perfect_match') then
      perform public.award_badge(uid, 'perfect_match');
    end if;
  end if;

  -- 9. three_exact (3 exact scores)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'three_exact') then
    select count(*) into exact_preds
    from public.predictions p
    inner join public.matches m on m.id = p.match_id
    where p.user_id = uid
      and m.status = 'finished'
      and p.predicted_home = m.home_score
      and p.predicted_away = m.away_score;
    if exact_preds >= 3 then
      perform public.award_badge(uid, 'three_exact');
    end if;
  end if;

  -- 10. ten_exact (10 exact scores)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'ten_exact') then
    select count(*) into exact_preds
    from public.predictions p
    inner join public.matches m on m.id = p.match_id
    where p.user_id = uid
      and m.status = 'finished'
      and p.predicted_home = m.home_score
      and p.predicted_away = m.away_score;
    if exact_preds >= 10 then
      perform public.award_badge(uid, 'ten_exact');
    end if;
  end if;

  -- 11. twenty_exact (20 exact scores)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'twenty_exact') then
    select count(*) into exact_preds
    from public.predictions p
    inner join public.matches m on m.id = p.match_id
    where p.user_id = uid
      and m.status = 'finished'
      and p.predicted_home = m.home_score
      and p.predicted_away = m.away_score;
    if exact_preds >= 20 then
      perform public.award_badge(uid, 'twenty_exact');
    end if;
  end if;

  -- 12. exact_draw (exact score and predicted_home = predicted_away)
  if is_exact_hit and NEW.predicted_home = NEW.predicted_away then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'exact_draw') then
      perform public.award_badge(uid, 'exact_draw');
    end if;
  end if;

  -- 13. high_scorer (exact score and either home or away prediction >= 4 goals)
  if is_exact_hit and (NEW.predicted_home >= 4 or NEW.predicted_away >= 4) then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'high_scorer') then
      perform public.award_badge(uid, 'high_scorer');
    end if;
  end if;

  -- 14. points_50, points_100, points_200 (accumulated points)
  select coalesce(sum(points), 0) into total_pts from public.predictions where user_id = uid;
  if total_pts >= 50 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'points_50') then
    perform public.award_badge(uid, 'points_50');
  end if;
  if total_pts >= 100 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'points_100') then
    perform public.award_badge(uid, 'points_100');
  end if;
  if total_pts >= 200 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'points_200') then
    perform public.award_badge(uid, 'points_200');
  end if;

  -- 15. nostradamus (3 exact scores consecutively, ordered by match_date desc)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'nostradamus') then
    with ordered_preds as (
      select 
        (p.predicted_home = m.home_score and p.predicted_away = m.away_score) as is_exact,
        lead(p.predicted_home = m.home_score and p.predicted_away = m.away_score, 1) over (order by m.match_date desc) as next_is_exact,
        lead(p.predicted_home = m.home_score and p.predicted_away = m.away_score, 2) over (order by m.match_date desc) as next_next_is_exact
      from public.predictions p
      inner join public.matches m on m.id = p.match_id
      where p.user_id = uid and m.status = 'finished'
    )
    select count(*) into consec_exact
    from ordered_preds
    where is_exact = true and next_is_exact = true and next_next_is_exact = true;

    if consec_exact > 0 then
      perform public.award_badge(uid, 'nostradamus');
    end if;
  end if;

  -- 16. invicto (points > 0 for all matches played on a single date)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'invicto') then
    with day_counts as (
      select (m.match_date at time zone 'UTC' at time zone 'America/Costa_Rica')::date as match_day,
             count(m.id) as total_matches,
             count(p.id) as user_predictions,
             count(case when p.points > 0 then 1 end) as positive_predictions
      from public.matches m
      left join public.predictions p on p.match_id = m.id and p.user_id = uid
      where m.status = 'finished'
      group by 1
    )
    select count(*) into invicto_days_count
    from day_counts
    where total_matches = user_predictions and total_matches = positive_predictions and total_matches > 0;

    if invicto_days_count > 0 then
      perform public.award_badge(uid, 'invicto');
    end if;
  end if;

  -- 17. group_a_clean (correct predictions of Group A matches - 6 matches total in group A)
  -- Group A matches: Mexico, Korea Republic, South Africa, Czechia
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'group_a_clean') then
    select count(*) into group_a_correct_count
    from public.predictions p
    inner join public.matches m on m.id = p.match_id
    where p.user_id = uid
      and m.stage_group = 'Grupo A'
      and m.status = 'finished'
      and p.points > 0;
    if group_a_correct_count = 6 then
      perform public.award_badge(uid, 'group_a_clean');
    end if;
  end if;

  -- 18. comeback_king (user correctly predicted the winner of a match that ended in a comeback)
  -- A comeback here is defined as a match where a team wins despite the other team scoring first (mocked simply in score points or logic)
  -- In this SQL trigger context, we simplify: user guessed winner correct when there was high scoring comeback.
  -- Let's check predictions with points = 3 or 5, where winner won, and check if total goals >= 3.
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'comeback_king') then
    select count(*) into comeback_king_count
    from public.predictions p
    inner join public.matches m on m.id = p.match_id
    where p.user_id = uid
      and p.points >= 3
      and m.status = 'finished'
      and ((m.home_score > m.away_score and m.away_score > 0) or (m.away_score > m.home_score and m.home_score > 0))
      and (m.home_score + m.away_score >= 3);
    if comeback_king_count >= 3 then
      perform public.award_badge(uid, 'comeback_king');
    end if;
  end if;

  return NEW;
end;
$$;

-- Create prediction trigger
drop trigger if exists trigger_check_prediction_badges on public.predictions;
create trigger trigger_check_prediction_badges
after insert or update on public.predictions
for each row
execute procedure public.trigger_check_prediction_badges();


-- 4. Trivia Trigger Function
create or replace function public.trigger_check_trivia_badges()
returns trigger
language plpgsql
security definer
as $$
declare
  uid uuid;
  total_answers int;
  correct_answers int;
  consec_correct int;
  consec_correct_seven int;
  consec_perfect_five int;
  total_trivia_pts int;
  answered_hour int;
  yesterday_answered boolean;
  consec_days_count int;
begin
  uid := NEW.user_id;

  -- 1. first_trivia
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_trivia') then
    perform public.award_badge(uid, 'first_trivia');
  end if;

  -- 2. perfect_trivia (correct answer)
  if NEW.is_correct then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'perfect_trivia') then
      perform public.award_badge(uid, 'perfect_trivia');
    end if;
  end if;

  -- 3. trivia_speed (time taken under 10 seconds)
  if NEW.is_correct and NEW.time_taken is not null and NEW.time_taken <= 10 then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_speed') then
      perform public.award_badge(uid, 'trivia_speed');
    end if;
  end if;

  -- 4. trivia_lucky (time taken near limit, let's say >= 28 seconds assuming 30s limit)
  if NEW.is_correct and NEW.time_taken is not null and NEW.time_taken >= 28 then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_lucky') then
      perform public.award_badge(uid, 'trivia_lucky');
    end if;
  end if;

  -- 5. three_trivia_streak (3 correct in a row)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'three_trivia_streak') then
    with ordered_answers as (
      select ta.is_correct,
             lead(ta.is_correct, 1) over (order by tq.trivia_date desc) as prev_1,
             lead(ta.is_correct, 2) over (order by tq.trivia_date desc) as prev_2
      from public.trivia_answers ta
      inner join public.trivia_questions tq on tq.id = ta.question_id
      where ta.user_id = uid
    )
    select count(*) into consec_correct
    from ordered_answers
    where is_correct = true and prev_1 = true and prev_2 = true;

    if consec_correct > 0 then
      perform public.award_badge(uid, 'three_trivia_streak');
    end if;
  end if;

  -- 6. seven_trivia_streak (7 correct in a row)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'seven_trivia_streak') then
    with ordered_answers as (
      select ta.is_correct,
             lead(ta.is_correct, 1) over (order by tq.trivia_date desc) as prev_1,
             lead(ta.is_correct, 2) over (order by tq.trivia_date desc) as prev_2,
             lead(ta.is_correct, 3) over (order by tq.trivia_date desc) as prev_3,
             lead(ta.is_correct, 4) over (order by tq.trivia_date desc) as prev_4,
             lead(ta.is_correct, 5) over (order by tq.trivia_date desc) as prev_5,
             lead(ta.is_correct, 6) over (order by tq.trivia_date desc) as prev_6
      from public.trivia_answers ta
      inner join public.trivia_questions tq on tq.id = ta.question_id
      where ta.user_id = uid
    )
    select count(*) into consec_correct_seven
    from ordered_answers
    where is_correct = true and prev_1 = true and prev_2 = true and prev_3 = true and prev_4 = true and prev_5 = true and prev_6 = true;

    if consec_correct_seven > 0 then
      perform public.award_badge(uid, 'seven_trivia_streak');
    end if;
  end if;

  -- 7. trivia_master (15 correct answers total)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_master') then
    select count(*) into correct_answers from public.trivia_answers where user_id = uid and is_correct = true;
    if correct_answers >= 15 then
      perform public.award_badge(uid, 'trivia_master');
    end if;
  end if;

  -- 8. trivia_half (answered 15 questions in total)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_half') then
    select count(*) into total_answers from public.trivia_answers where user_id = uid;
    if total_answers >= 15 then
      perform public.award_badge(uid, 'trivia_half');
    end if;
  end if;

  -- 9. trivia_all (answered all available questions)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_all') then
    select count(*) into total_answers from public.trivia_answers where user_id = uid;
    if total_answers = (select count(*) from public.trivia_questions) then
      perform public.award_badge(uid, 'trivia_all');
    end if;
  end if;

  -- 10. trivia_night_owl (answered between 11:00 PM and 4:00 AM local time)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_night_owl') then
    answered_hour := extract(hour from NEW.answered_at at time zone 'America/Costa_Rica');
    if answered_hour >= 23 or answered_hour < 4 then
      perform public.award_badge(uid, 'trivia_night_owl');
    end if;
  end if;

  -- 11. trivia_morning (answered before 7:00 AM local time)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_morning') then
    answered_hour := extract(hour from NEW.answered_at at time zone 'America/Costa_Rica');
    if answered_hour >= 4 and answered_hour < 7 then
      perform public.award_badge(uid, 'trivia_morning');
    end if;
  end if;

  -- 12. trivia_genius (accumulated trivia points >= 100)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_genius') then
    select coalesce(sum(points), 0) into total_trivia_pts from public.trivia_answers where user_id = uid;
    if total_trivia_pts >= 100 then
      perform public.award_badge(uid, 'trivia_genius');
    end if;
  end if;

  -- 13. trivia_fanatic (answered trivia questions 5 days in a row)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_fanatic') then
    with dates as (
      select distinct (ta.answered_at at time zone 'America/Costa_Rica')::date as ans_date
      from public.trivia_answers ta
      where ta.user_id = uid
    ),
    diffs as (
      select ans_date,
             ans_date - (row_number() over (order by ans_date))::int as grp
      from dates
    )
    select count(*) into consec_days_count
    from diffs
    group by grp
    order by count(*) desc
    limit 1;

    if consec_days_count >= 5 then
      perform public.award_badge(uid, 'trivia_fanatic');
    end if;
  end if;

  -- 14. trivia_comeback (answered correct after incorrect)
  if NEW.is_correct and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_comeback') then
    with prev_ans as (
      select ta.is_correct
      from public.trivia_answers ta
      inner join public.trivia_questions tq on tq.id = ta.question_id
      where ta.user_id = uid and ta.id != NEW.id
      order by tq.trivia_date desc
      limit 1
    )
    select not is_correct into yesterday_answered from prev_ans;
    if yesterday_answered then
      perform public.award_badge(uid, 'trivia_comeback');
    end if;
  end if;

  -- 15. trivia_perfect_score (puntuación máxima 10 en 5 trivias consecutivas)
  if NEW.points = 10 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'trivia_perfect_score') then
    with ordered_answers as (
      select ta.points,
             lead(ta.points, 1) over (order by ta.answered_at desc) as prev_1,
             lead(ta.points, 2) over (order by ta.answered_at desc) as prev_2,
             lead(ta.points, 3) over (order by ta.answered_at desc) as prev_3,
             lead(ta.points, 4) over (order by ta.answered_at desc) as prev_4
      from public.trivia_answers ta
      where ta.user_id = uid
    )
    select count(*) into consec_perfect_five
    from ordered_answers
    where points = 10 and prev_1 = 10 and prev_2 = 10 and prev_3 = 10 and prev_4 = 10;

    if consec_perfect_five > 0 then
      perform public.award_badge(uid, 'trivia_perfect_score');
    end if;
  end if;

  return NEW;
end;
$$;

-- Create trivia trigger
drop trigger if exists trigger_check_trivia_badges on public.trivia_answers;
create trigger trigger_check_trivia_badges
after insert on public.trivia_answers
for each row
execute procedure public.trigger_check_trivia_badges();


-- 5. Chat Trigger Function
create or replace function public.trigger_check_social_badges()
returns trigger
language plpgsql
security definer
as $$
declare
  uid uuid;
  total_comments int;
  lobby_comments_count int;
  match_comments_count int;
  distinct_matches int;
begin
  uid := NEW.user_id;

  -- 1. first_comment
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_comment') then
    perform public.award_badge(uid, 'first_comment');
  end if;

  -- Get counts
  select (select count(*) from public.lobby_comments where user_id = uid) +
         (select count(*) from public.match_comments where user_id = uid)
         into total_comments;

  -- 2. ten_comments (10 messages)
  if total_comments >= 10 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'ten_comments') then
    perform public.award_badge(uid, 'ten_comments');
  end if;

  -- 3. fifty_comments (50 messages)
  if total_comments >= 50 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'fifty_comments') then
    perform public.award_badge(uid, 'fifty_comments');
  end if;

  -- 4. spammer (100 messages)
  if total_comments >= 100 and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'spammer') then
    perform public.award_badge(uid, 'spammer');
  end if;

  -- 5. first_gif (comment containing a link to giphy)
  if (NEW.comment like '%giphy.com/media/%' or NEW.comment like '%.gif%') and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_gif') then
    perform public.award_badge(uid, 'first_gif');
  end if;

  -- 6. first_mention (comment containing a mention '@')
  if NEW.comment like '%@%' and not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_mention') then
    perform public.award_badge(uid, 'first_mention');
  end if;

  -- 7. lobby_chatter (5+ comments in lobby)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'lobby_chatter') then
    select count(*) into lobby_comments_count from public.lobby_comments where user_id = uid;
    if lobby_comments_count >= 5 then
      perform public.award_badge(uid, 'lobby_chatter');
    end if;
  end if;

  -- 8. match_chatter (1+ comment in match chats)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'match_chatter') then
    select count(*) into match_comments_count from public.match_comments where user_id = uid;
    if match_comments_count >= 1 then
      perform public.award_badge(uid, 'match_chatter');
    end if;
  end if;

  -- 9. five_chats (chatted on 5 distinct matches)
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'five_chats') then
    select count(distinct match_id) into distinct_matches from public.match_comments where user_id = uid;
    if distinct_matches >= 5 then
      perform public.award_badge(uid, 'five_chats');
    end if;
  end if;

  -- 10. friendly (checks if someone else mentioned this user)
  -- Handled by checks when someone else mentions this username, but we also check if their username matches the mention
  -- To make it easy, we trigger this when the NEW comment contains their name OR we check it reactively.
  -- To keep it super simple, we can run this detection. However, another user mentioned is triggered by the comment text.
  -- We'll handle 'friendly' when a comment containing "@username" is processed.
  -- Let's extract the username in plpgsql and award the badge to the target user:
  declare
    mentioned_username text;
    mentioned_user_id uuid;
    at_index int;
    cleaned_comment text;
  begin
    cleaned_comment := NEW.comment;
    at_index := position('@' in cleaned_comment);
    if at_index > 0 then
      -- Simple extraction: characters after @ until space
      mentioned_username := split_part(substring(cleaned_comment from at_index + 1), ' ', 1);
      -- Clean it from common punctuation
      mentioned_username := regexp_replace(mentioned_username, '[^a-zA-Z0-9_\-\.]', '', 'g');
      
      -- Find user ID
      select id into mentioned_user_id 
      from auth.users 
      where email = mentioned_username || '@quiniela.local';
      
      if mentioned_user_id is not null and mentioned_user_id != uid then
        if not exists (select 1 from public.user_badges where user_id = mentioned_user_id and badge_key = 'friendly') then
          perform public.award_badge(mentioned_user_id, 'friendly');
        end if;
      end if;
    end if;
  end;

  return NEW;
end;
$$;

-- Create social triggers
drop trigger if exists trigger_check_lobby_social_badges on public.lobby_comments;
create trigger trigger_check_lobby_social_badges
after insert on public.lobby_comments
for each row
execute procedure public.trigger_check_social_badges();

drop trigger if exists trigger_check_match_social_badges on public.match_comments;
create trigger trigger_check_match_social_badges
after insert on public.match_comments
for each row
execute procedure public.trigger_check_social_badges();


-- 6. Logins Trigger Function
create or replace function public.trigger_check_login_badges()
returns trigger
language plpgsql
security definer
as $$
declare
  uid uuid;
  has_three_day boolean;
  has_seven_day boolean;
  has_fifteen_day boolean;
begin
  uid := NEW.user_id;

  -- 1. first_login
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'first_login') then
    perform public.award_badge(uid, 'first_login');
  end if;

  -- 2. three_days_streak
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'three_days_streak') then
    select count(*) = 3 into has_three_day
    from public.user_logins
    where user_id = uid
      and login_date >= NEW.login_date - 2
      and login_date <= NEW.login_date;
      
    if has_three_day then
      perform public.award_badge(uid, 'three_days_streak');
    end if;
  end if;

  -- 3. seven_days_streak
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'seven_days_streak') then
    select count(*) = 7 into has_seven_day
    from public.user_logins
    where user_id = uid
      and login_date >= NEW.login_date - 6
      and login_date <= NEW.login_date;
      
    if has_seven_day then
      perform public.award_badge(uid, 'seven_days_streak');
    end if;
  end if;

  -- 4. fifteen_days_streak
  if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'fifteen_days_streak') then
    select count(*) = 15 into has_fifteen_day
    from public.user_logins
    where user_id = uid
      and login_date >= NEW.login_date - 14
      and login_date <= NEW.login_date;
      
    if has_fifteen_day then
      perform public.award_badge(uid, 'fifteen_days_streak');
    end if;
  end if;

  -- 5. final_day_login (logged in on July 19th, 2026 - Day of the Final)
  if NEW.login_date = '2026-07-19'::date then
    if not exists (select 1 from public.user_badges where user_id = uid and badge_key = 'final_day_login') then
      perform public.award_badge(uid, 'final_day_login');
    end if;
  end if;

  return NEW;
end;
$$;

-- Create login trigger
drop trigger if exists trigger_check_login_badges on public.user_logins;
create trigger trigger_check_login_badges
after insert on public.user_logins
for each row
execute procedure public.trigger_check_login_badges();
