-- ==========================================
-- MATCH COMMENTS & REALTIME CHAT SYSTEM
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Create Match Comments Table
create table if not exists public.match_comments (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null default 'anon',
  comment text not null check (length(comment) <= 500),
  created_at timestamptz not null default now()
);

-- Index for fast retrieval of comments for a match
create index if not exists match_comments_match_id_idx on public.match_comments (match_id, created_at asc);

-- Enable Row Level Security (RLS)
alter table public.match_comments enable row level security;

-- ==========================================
-- RLS Policies
-- ==========================================

-- Anyone (authenticated or public) can read match comments
drop policy if exists match_comments_select_all on public.match_comments;
create policy match_comments_select_all on public.match_comments
  for select using (true);

-- Authenticated users can post comments as themselves
drop policy if exists match_comments_insert_own on public.match_comments;
create policy match_comments_insert_own on public.match_comments
  for insert with check (auth.uid() = user_id);

-- Users and admin can delete comments
drop policy if exists match_comments_delete_own on public.match_comments;
create policy match_comments_delete_own on public.match_comments
  for delete using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- ==========================================
-- Trigger Function: set_comment_username
-- Automatically resolves and stores user's email username prefix
-- to avoid spoofing in client-side payloads.
-- ==========================================
create or replace function public.set_comment_username()
returns trigger
language plpgsql
security definer
as $$
declare
  user_email text;
begin
  select email into user_email from auth.users where id = new.user_id;
  new.username := coalesce(split_part(user_email, '@', 1), 'anon');
  return new;
end;
$$;

-- Trigger: before insert
drop trigger if exists trigger_set_comment_username on public.match_comments;
create trigger trigger_set_comment_username
before insert on public.match_comments
for each row
execute procedure public.set_comment_username();

-- ==========================================
-- Enable Realtime for the match_comments table
-- ==========================================
do $$
begin
  alter publication supabase_realtime add table public.match_comments;
exception
  when others then
    -- If the publication doesn't exist yet or is configured differently, log it (non-blocking)
    raise notice 'No se pudo agregar a la publicación supabase_realtime directamente. Por favor habilítalo desde el panel.';
end;
$$;

-- ==========================================
-- LOBBY COMMENTS (GENERAL CHAT) SYSTEM
-- ==========================================

-- 1. Create Lobby Comments Table
create table if not exists public.lobby_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null default 'anon',
  comment text not null check (length(comment) <= 500),
  created_at timestamptz not null default now()
);

-- Index for fast retrieval of lobby comments
create index if not exists lobby_comments_created_at_idx on public.lobby_comments (created_at asc);

-- Enable Row Level Security (RLS)
alter table public.lobby_comments enable row level security;

-- RLS Policies for lobby_comments
drop policy if exists lobby_comments_select_all on public.lobby_comments;
create policy lobby_comments_select_all on public.lobby_comments
  for select using (true);

drop policy if exists lobby_comments_insert_own on public.lobby_comments;
create policy lobby_comments_insert_own on public.lobby_comments
  for insert with check (auth.uid() = user_id);

drop policy if exists lobby_comments_delete_own on public.lobby_comments;
create policy lobby_comments_delete_own on public.lobby_comments
  for delete using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- Trigger: before insert
drop trigger if exists trigger_set_lobby_comment_username on public.lobby_comments;
create trigger trigger_set_lobby_comment_username
before insert on public.lobby_comments
for each row
execute procedure public.set_comment_username();

-- Enable Realtime for the lobby_comments table
do $$
begin
  alter publication supabase_realtime add table public.lobby_comments;
exception
  when others then
    raise notice 'No se pudo agregar a la publicación supabase_realtime directamente. Por favor habilítalo desde el panel.';
end;
$$;
