-- ==========================================
-- MATCH COMMENTS & REALTIME CHAT SYSTEM
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Create Match Comments Table
create table if not exists public.match_comments (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null default 'anon',
  comment text not null check (length(comment) <= 500),
  created_at timestamptz not null default now()
);

-- Index for fast retrieval of comments for a match
create index if not exists match_comments_match_id_idx on public.match_comments (match_id, created_at asc);

-- Enable Row Level Security (RLS)
alter table public.match_comments enable row level security;

-- ==========================================
-- RLS Policies
-- ==========================================

-- Anyone (authenticated or public) can read match comments
drop policy if exists match_comments_select_all on public.match_comments;
create policy match_comments_select_all on public.match_comments
  for select using (true);

-- Authenticated users can post comments as themselves
drop policy if exists match_comments_insert_own on public.match_comments;
create policy match_comments_insert_own on public.match_comments
  for insert with check (auth.uid() = user_id);

-- Users and admin can delete comments
drop policy if exists match_comments_delete_own on public.match_comments;
create policy match_comments_delete_own on public.match_comments
  for delete using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- ==========================================
-- Trigger Function: set_comment_username
-- Automatically resolves and stores user's email username prefix
-- to avoid spoofing in client-side payloads.
-- ==========================================
create or replace function public.set_comment_username()
returns trigger
language plpgsql
security definer
as $$
declare
  user_email text;
begin
  select email into user_email from auth.users where id = new.user_id;
  new.username := coalesce(split_part(user_email, '@', 1), 'anon');
  return new;
end;
$$;

-- Trigger: before insert
drop trigger if exists trigger_set_comment_username on public.match_comments;
create trigger trigger_set_comment_username
before insert on public.match_comments
for each row
execute procedure public.set_comment_username();

-- ==========================================
-- Enable Realtime for the match_comments table
-- ==========================================
do $$
begin
  alter publication supabase_realtime add table public.match_comments;
exception
  when others then
    -- If the publication doesn't exist yet or is configured differently, log it (non-blocking)
    raise notice 'No se pudo agregar a la publicación supabase_realtime directamente. Por favor habilítalo desde el panel.';
end;
$$;

-- ==========================================
-- LOBBY COMMENTS (GENERAL CHAT) SYSTEM
-- ==========================================

-- 1. Create Lobby Comments Table
create table if not exists public.lobby_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null default 'anon',
  comment text not null check (length(comment) <= 500),
  created_at timestamptz not null default now()
);

-- Index for fast retrieval of lobby comments
create index if not exists lobby_comments_created_at_idx on public.lobby_comments (created_at asc);

-- Enable Row Level Security (RLS)
alter table public.lobby_comments enable row level security;

-- RLS Policies for lobby_comments
drop policy if exists lobby_comments_select_all on public.lobby_comments;
create policy lobby_comments_select_all on public.lobby_comments
  for select using (true);

drop policy if exists lobby_comments_insert_own on public.lobby_comments;
create policy lobby_comments_insert_own on public.lobby_comments
  for insert with check (auth.uid() = user_id);

drop policy if exists lobby_comments_delete_own on public.lobby_comments;
create policy lobby_comments_delete_own on public.lobby_comments
  for delete using (auth.uid() = user_id or auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- Trigger: before insert
drop trigger if exists trigger_set_lobby_comment_username on public.lobby_comments;
create trigger trigger_set_lobby_comment_username
before insert on public.lobby_comments
for each row
execute procedure public.set_comment_username();

-- Enable Realtime for the lobby_comments table
do $$
begin
  alter publication supabase_realtime add table public.lobby_comments;
exception
  when others then
    raise notice 'No se pudo agregar a la publicación supabase_realtime directamente. Por favor habilítalo desde el panel.';
end;
$$;

-- Clean up old shared function and triggers if they exist (dropping triggers first to avoid dependency errors)
drop trigger if exists trigger_generate_match_comment_mentions on public.match_comments;
drop trigger if exists trigger_generate_lobby_comment_mentions on public.lobby_comments;
drop trigger if exists trigger_generate_comment_mentions on public.match_comments;
drop trigger if exists trigger_generate_comment_mentions on public.lobby_comments;
drop function if exists public.generate_comment_mentions();

-- ==========================================
-- Trigger Function: generate_match_comment_mentions
-- Automatically scans match comments for @username mentions,
-- resolves their user_id, and inserts an in-app notification.
-- ==========================================
create or replace function public.generate_match_comment_mentions()
returns trigger
language plpgsql
security definer
as $$
declare
  r record;
  target_user_id uuid;
  mentioned_uname text;
  channel_name text;
begin
  -- Fast check: if the comment does not contain '@', skip regex search
  if position('@' in new.comment) = 0 then
    return new;
  end if;

  -- Resolve match teams
  select (m.home_team || ' vs ' || m.away_team) into channel_name
  from public.matches m
  where m.id = new.match_id;
  channel_name := '#' || coalesce(channel_name, 'partido');

  -- Find all distinct mentions using regular expression
  for r in 
    select distinct regexp_replace(m[1], '^@', '') as uname
    from (
      select regexp_matches(new.comment, '@([a-zA-Z0-9_\-\.]+)', 'g') as m
    ) sub
  loop
    mentioned_uname := r.uname;
    
    -- Find target user ID matching the email prefix
    select id into target_user_id
    from auth.users
    where lower(split_part(email, '@', 1)) = lower(mentioned_uname)
    limit 1;

    -- If target user exists and is not the sender, create a notification
    if target_user_id is not null and target_user_id != new.user_id then
      insert into public.notifications (user_id, type, title, body, match_id)
      values (
        target_user_id,
        'chat_mention',
        '💬 Mención en ' || channel_name,
        new.username || ': "' || substring(new.comment from 1 for 80) || '"',
        new.match_id
      );
    end if;
  end loop;

  return new;
end;
$$;

-- ==========================================
-- Trigger Function: generate_lobby_comment_mentions
-- Automatically scans general lobby comments for @username mentions,
-- resolves their user_id, and inserts an in-app notification.
-- ==========================================
create or replace function public.generate_lobby_comment_mentions()
returns trigger
language plpgsql
security definer
as $$
declare
  r record;
  target_user_id uuid;
  mentioned_uname text;
begin
  -- Fast check: if the comment does not contain '@', skip regex search
  if position('@' in new.comment) = 0 then
    return new;
  end if;

  -- Find all distinct mentions using regular expression
  for r in 
    select distinct regexp_replace(m[1], '^@', '') as uname
    from (
      select regexp_matches(new.comment, '@([a-zA-Z0-9_\-\.]+)', 'g') as m
    ) sub
  loop
    mentioned_uname := r.uname;
    
    -- Find target user ID matching the email prefix
    select id into target_user_id
    from auth.users
    where lower(split_part(email, '@', 1)) = lower(mentioned_uname)
    limit 1;

    -- If target user exists and is not the sender, create a notification
    if target_user_id is not null and target_user_id != new.user_id then
      insert into public.notifications (user_id, type, title, body, match_id)
      values (
        target_user_id,
        'chat_mention',
        '💬 Mención en #general',
        new.username || ': "' || substring(new.comment from 1 for 80) || '"',
        null
      );
    end if;
  end loop;

  return new;
end;
$$;

-- Trigger for match_comments
drop trigger if exists trigger_generate_match_comment_mentions on public.match_comments;
create trigger trigger_generate_match_comment_mentions
after insert on public.match_comments
for each row
execute procedure public.generate_match_comment_mentions();

-- Trigger for lobby_comments
drop trigger if exists trigger_generate_lobby_comment_mentions on public.lobby_comments;
create trigger trigger_generate_lobby_comment_mentions
after insert on public.lobby_comments
for each row
execute procedure public.generate_lobby_comment_mentions();
