-- ==========================================
-- NOTIFICATIONS SYSTEM
-- Run this in Supabase SQL Editor after the main schema
-- ==========================================

-- 1. Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'match_result',
  title text not null,
  body text not null,
  match_id bigint references public.matches(id) on delete set null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Index for fast lookups by user
create index if not exists notifications_user_id_idx on public.notifications (user_id, created_at desc);
create index if not exists notifications_unread_idx on public.notifications (user_id) where is_read = false;

-- Enable RLS
alter table public.notifications enable row level security;

-- 2. RLS Policies

-- Users can only see their own notifications
drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications
  for select
  using (auth.uid() = user_id);

-- Users can update their own notifications (to mark as read)
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can delete their own notifications
drop policy if exists notifications_delete_own on public.notifications;
create policy notifications_delete_own on public.notifications
  for delete
  using (auth.uid() = user_id);

-- No direct insert policy for users — notifications are created by triggers (security definer)


-- 3. Trigger Function: Generate notifications when a match finishes
create or replace function public.generate_match_notifications()
returns trigger
language plpgsql
security definer
as $$
declare
  pred_rec record;
  pts int;
  notif_title text;
  notif_body text;
  notif_type text;
  match_label text;
  streak int;
  prev_rec record;
  had_streak boolean;
begin
  -- Only fire when a match transitions to 'finished' or scores change while finished
  if (new.status = 'finished') and 
     (old.status is distinct from 'finished' or 
      old.home_score is distinct from new.home_score or 
      old.away_score is distinct from new.away_score) then

    match_label := new.home_team || ' ' || new.home_score || '-' || new.away_score || ' ' || new.away_team;

    -- Delete old notifications for this match (in case scores were corrected)
    delete from public.notifications where match_id = new.id and type = 'match_result';
    delete from public.notifications where match_id = new.id and type in ('streak_started', 'streak_broken');

    for pred_rec in 
      select p.*, p.points as current_points
      from public.predictions p 
      where p.match_id = new.id 
    loop
      -- Read the freshly-calculated points (the scoring trigger runs before this one at AFTER UPDATE priority)
      select points into pts from public.predictions where id = pred_rec.id;

      -- Build notification message based on points
      if pts = 5 then
        notif_title := '🎯 ¡Marcador Exacto!';
        notif_body := match_label || ' — Predijiste ' || pred_rec.predicted_home || '-' || pred_rec.predicted_away || '. ¡+5 pts!';
        notif_type := 'match_result';
      elsif pts >= 3 then
        notif_title := '⚽ ¡Ganador Correcto!';
        notif_body := match_label || ' — Predijiste ' || pred_rec.predicted_home || '-' || pred_rec.predicted_away || '. +' || pts || ' pts';
        notif_type := 'match_result';
      elsif pts >= 1 then
        notif_title := '🤝 ¡Empate Acertado!';
        notif_body := match_label || ' — Predijiste ' || pred_rec.predicted_home || '-' || pred_rec.predicted_away || '. +' || pts || ' pt';
        notif_type := 'match_result';
      else
        notif_title := '❌ No Acertaste';
        notif_body := match_label || ' — Predijiste ' || pred_rec.predicted_home || '-' || pred_rec.predicted_away || '. 0 pts';
        notif_type := 'match_result';
      end if;

      -- Insert the match result notification
      insert into public.notifications (user_id, type, title, body, match_id)
      values (pred_rec.user_id, notif_type, notif_title, notif_body, new.id);

      -- Check streak status for this user
      if pts > 0 then
        streak := 0;
        for prev_rec in
          select p.points
          from public.predictions p
          inner join public.matches m on m.id = p.match_id
          where p.user_id = pred_rec.user_id
            and m.status = 'finished'
            and m.match_date <= new.match_date
          order by m.match_date desc
        loop
          if prev_rec.points > 0 then
            streak := streak + 1;
          else
            exit;
          end if;
        end loop;

        -- Notify when streak just reached 3
        if streak = 3 then
          insert into public.notifications (user_id, type, title, body, match_id)
          values (
            pred_rec.user_id,
            'streak_started',
            '🔥 ¡Racha On Fire!',
            '¡Llevas ' || streak || ' aciertos consecutivos! Tus puntos ahora se multiplican x1.5.',
            new.id
          );
        elsif streak > 3 then
          insert into public.notifications (user_id, type, title, body, match_id)
          values (
            pred_rec.user_id,
            'streak_started',
            '🔥 ¡Racha Imparable!',
            '¡Llevas ' || streak || ' aciertos seguidos! Sigues con el multiplicador x1.5.',
            new.id
          );
        end if;

      else
        -- User got 0 points, check if they HAD a streak before
        had_streak := false;
        streak := 0;
        for prev_rec in
          select p.points
          from public.predictions p
          inner join public.matches m on m.id = p.match_id
          where p.user_id = pred_rec.user_id
            and m.status = 'finished'
            and m.match_date < new.match_date
          order by m.match_date desc
        loop
          if prev_rec.points > 0 then
            streak := streak + 1;
          else
            exit;
          end if;
        end loop;

        if streak >= 3 then
          insert into public.notifications (user_id, type, title, body, match_id)
          values (
            pred_rec.user_id,
            'streak_broken',
            '💔 Racha Rota',
            'Tu racha de ' || streak || ' aciertos se rompió. ¡A construir una nueva!',
            new.id
          );
        end if;
      end if;

    end loop;
  end if;

  return new;
end;
$$;

-- Trigger: fires after update on matches (after the scoring trigger)
drop trigger if exists trigger_generate_match_notifications on public.matches;
create trigger trigger_generate_match_notifications
after update on public.matches
for each row
execute procedure public.generate_match_notifications();


-- 4. RPC: Mark all notifications as read for the current user
create or replace function public.mark_notifications_read()
returns void
language plpgsql
security definer
as $$
begin
  update public.notifications
  set is_read = true
  where user_id = auth.uid()
    and is_read = false;
end;
$$;


-- 5. RPC: Get unread notification count for the current user
create or replace function public.get_unread_notification_count()
returns bigint
language plpgsql
security definer
as $$
declare
  cnt bigint;
begin
  select count(*) into cnt
  from public.notifications
  where user_id = auth.uid()
    and is_read = false;
  return cnt;
end;
$$;


-- 6. RPC: Delete all notifications for the current user
create or replace function public.clear_all_notifications()
returns void
language plpgsql
security definer
as $$
begin
  delete from public.notifications
  where user_id = auth.uid();
end;
$$;


-- ==========================================
-- IMPORTANT: After running this migration, enable Realtime for the notifications table:
-- 1. Go to your Supabase Dashboard
-- 2. Navigate to Database → Replication
-- 3. Under "supabase_realtime", click the toggle for the "notifications" table
-- This allows the frontend to receive live INSERT events via Supabase Realtime.
-- ==========================================
