-- =======================================================
-- PUSH NOTIFICATIONS SUBSCRIPTIONS MIGRATION
-- Run this in the Supabase SQL Editor
-- =======================================================

-- 1. Create table
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  constraint push_subscriptions_endpoint_unique unique (endpoint)
);

-- 2. Add indexes for fast querying by user
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions (user_id);

-- 3. Enable Row Level Security (RLS)
alter table public.push_subscriptions enable row level security;

-- 4. Set RLS Policies
-- Select policy: users can only see their own subscriptions
drop policy if exists push_subscriptions_select_own on public.push_subscriptions;
create policy push_subscriptions_select_own on public.push_subscriptions
  for select
  using (auth.uid() = user_id);

-- Insert policy: users can only register their own subscriptions
drop policy if exists push_subscriptions_insert_own on public.push_subscriptions;
create policy push_subscriptions_insert_own on public.push_subscriptions
  for insert
  with check (auth.uid() = user_id);

-- Delete policy: users can only delete their own subscriptions
drop policy if exists push_subscriptions_delete_own on public.push_subscriptions;
create policy push_subscriptions_delete_own on public.push_subscriptions
  for delete
  using (auth.uid() = user_id);
