-- Quiniela Supabase schema and RLS policies

-- Matches Table
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  home_team text not null,
  away_team text not null,
  match_date timestamptz not null,
  home_score int,
  away_score int,
  status text not null default 'pending',
  score_manually_set boolean not null default false
);

-- Predictions Table
create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  predicted_home int not null,
  predicted_away int not null,
  points int not null default 0,
  created_at timestamptz not null default now()
);

-- Ensure user can make only one prediction per match
create unique index if not exists predictions_user_match_unique on public.predictions (user_id, match_id);

-- Enable Row Level Security
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

-- RLS Policies for Matches
drop policy if exists public_matches_select on public.matches;
create policy public_matches_select on public.matches
  for select
  using (true);

drop policy if exists matches_insert_auth on public.matches;
create policy matches_insert_auth on public.matches
  for insert
  with check (auth.jwt() ->> 'email' = 'admin@quiniela.local');

drop policy if exists matches_update_auth on public.matches;
create policy matches_update_auth on public.matches
  for update
  using (auth.jwt() ->> 'email' = 'admin@quiniela.local')
  with check (auth.jwt() ->> 'email' = 'admin@quiniela.local');

drop policy if exists matches_delete_auth on public.matches;
create policy matches_delete_auth on public.matches
  for delete
  using (auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- RLS Policies for Predictions
drop policy if exists predictions_select_public on public.predictions;
create policy predictions_select_public on public.predictions
  for select
  using (true);

drop policy if exists predictions_insert_own on public.predictions;
create policy predictions_insert_own on public.predictions
  for insert
  with check (auth.uid() = user_id);

drop policy if exists predictions_update_own on public.predictions;
create policy predictions_update_own on public.predictions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists predictions_delete_own on public.predictions;
create policy predictions_delete_own on public.predictions
  for delete
  using (auth.uid() = user_id);

-- Scoring Function: Calculates points when a match changes to 'finished' or when scores are corrected.
create or replace function public.update_prediction_points()
returns trigger
language plpgsql
security definer
as $$
declare
  pred_rec record;
  prev_rec record;
  base_pts int;
  streak int;
  final_pts int;
begin
  if (new.status = 'finished') and 
     (old.status is distinct from 'finished' or 
      old.home_score is distinct from new.home_score or 
      old.away_score is distinct from new.away_score) then
    
    for pred_rec in select * from public.predictions where match_id = new.id loop
      -- Calculate base points
      base_pts := case
        when new.home_score = pred_rec.predicted_home and new.away_score = pred_rec.predicted_away then 5
        when sign(new.home_score - new.away_score) = sign(pred_rec.predicted_home - pred_rec.predicted_away) then
          case when new.home_score = new.away_score then 1 else 3 end
        else 0
      end;

      -- If the user scored, check their streak on previous matches
      if base_pts > 0 then
        streak := 0;
        for prev_rec in
          select p.points
          from public.predictions p
          inner join public.matches m on m.id = p.match_id
          where p.user_id = pred_rec.user_id
            and m.status = 'finished'
            and m.match_date < new.match_date
          order by m.match_date desc
        loop
          if prev_rec.points > 0 then
            streak := streak + 1;
          else
            exit;
          end if;
        end loop;

        -- Apply x1.5 multiplier if streak >= 3 consecutive wins before this match
        if streak >= 3 then
          final_pts := ceil(base_pts * 1.5);
        else
          final_pts := base_pts;
        end if;
      else
        final_pts := 0;
      end if;

      update public.predictions set points = final_pts where id = pred_rec.id;
    end loop;

  elsif (new.status = 'pending' and old.status = 'finished') then
    update public.predictions p
    set points = 0
    where p.match_id = new.id;
  end if;

  return new;
end;
$$;

-- Trigger to execute scoring logic after a match is updated
drop trigger if exists trigger_update_prediction_points on public.matches;
create trigger trigger_update_prediction_points
after update on public.matches
for each row
execute procedure public.update_prediction_points();

-- Time Lock Function: Prevents users from inserting/updating predictions less than 1 hour before kickoff.
create or replace function public.check_prediction_lock()
returns trigger
language plpgsql
security definer
as $$
declare
  match_kickoff timestamptz;
begin
  -- Bypass lock checks during database seeding operations
  if current_setting('my.seeding_mode', true) = 'on' then
    return new;
  end if;

  -- For updates, only enforce the lock if the predicted scores are actually changing.
  -- This allows the system to update points, metadata, etc., even after kickoff.
  if (TG_OP = 'UPDATE') and 
     (old.predicted_home = new.predicted_home) and 
     (old.predicted_away = new.predicted_away) then
    return new;
  end if;

  select match_date into match_kickoff from public.matches where id = new.match_id;
  
  if match_kickoff is null then
    raise exception 'Match not found';
  end if;
  
  if now() >= match_kickoff - interval '5 minutes' then
    raise exception 'Predictions are locked for this match.';
  end if;
  
  return new;
end;
$$;

-- Trigger to enforce time lock check before creating or updating predictions
drop trigger if exists trigger_check_prediction_lock on public.predictions;
create trigger trigger_check_prediction_lock
before insert or update on public.predictions
for each row
execute procedure public.check_prediction_lock();

-- Function to seed 5 dummy users and generate random predictions for all matches
create or replace function public.seed_dummies_and_predictions()
returns text
language plpgsql
security definer
as $$
declare
  dummy_usernames text[] := array['dummy_juan', 'dummy_sofia', 'dummy_diego', 'dummy_lucia', 'dummy_carlos'];
  d_username text;
  d_email text;
  d_id uuid;
  m_record record;
  p_home int;
  p_away int;
  created_count int := 0;
  pred_count int := 0;
begin
  -- Habilita el modo seeding para saltar el trigger del bloqueo de tiempo
  perform set_config('my.seeding_mode', 'on', true);

  foreach d_username in array dummy_usernames loop
    d_email := d_username || '@quiniela.local';
    
    -- Check if user exists
    select id into d_id from auth.users where email = d_email;
    
    if d_id is null then
      d_id := gen_random_uuid();
      
      -- Insert into auth.users (minimum required columns for Supabase auth setup)
      insert into auth.users (
        id,
        instance_id,
        email,
        encrypted_password,
        email_confirmed_at,
        raw_app_meta_data,
        raw_user_meta_data,
        created_at,
        updated_at,
        role,
        aud,
        confirmation_token
      )
      values (
        d_id,
        '00000000-0000-0000-0000-000000000000',
        d_email,
        -- Hash password 'password123'
        crypt('password123', gen_salt('bf')),
        now(),
        '{"provider":"email","providers":["email"]}',
        '{}',
        now(),
        now(),
        'authenticated',
        'authenticated',
        ''
      );
      
      created_count := created_count + 1;
    end if;

    -- Delete old predictions for this dummy user to reset state
    delete from public.predictions where user_id = d_id;

    -- Create random predictions for all matches in the database
    for m_record in select id, status, home_score, away_score from public.matches loop
      -- Generate random goals between 0 and 4
      p_home := floor(random() * 5);
      p_away := floor(random() * 5);
      
      -- Insert prediction (bypassing time lock trigger by inserting directly via security definer function)
      insert into public.predictions (user_id, match_id, predicted_home, predicted_away, points)
      values (
        d_id, 
        m_record.id, 
        p_home, 
        p_away,
        -- Pre-calculate points immediately if the match is finished
        case
          when m_record.status = 'finished' then
            case
              when m_record.home_score = p_home and m_record.away_score = p_away then 5
              when sign(m_record.home_score - m_record.away_score) = sign(p_home - p_away) then
                case
                  when m_record.home_score = m_record.away_score then 1
                  else 3
                end
              else 0
            end
          else 0
        end
      );
      
      pred_count := pred_count + 1;
    end loop;
  end loop;

  return '¡Se crearon/verificaron los 5 usuarios dummy con éxito! Se registraron ' || pred_count || ' pronósticos aleatorios en total.';
end;
$$;

-- Function to compute leaderboard grouped by username showing points and counts
create or replace function public.get_leaderboard()
returns table(username text, total_points bigint, predictions_count bigint)
language plpgsql
security definer
as $$
declare
  curr_phase int;
begin
  -- Determine current active phase based on first pending match
  select 
    case 
      when min(id) is null then 6
      when min(id) <= 72 then 1
      when min(id) <= 88 then 2
      when min(id) <= 96 then 3
      when min(id) <= 100 then 4
      when min(id) <= 102 then 5
      else 6
    end into curr_phase
  from public.matches
  where status != 'finished';

  if curr_phase is null then
    curr_phase := 6;
  end if;

  return query
  select 
    split_part(u.email, '@', 1)::text as username,
    (
      coalesce(sum(case 
        when curr_phase = 1 and p.match_id >= 1 and p.match_id <= 72 then p.points
        when curr_phase = 2 and p.match_id >= 73 and p.match_id <= 88 then p.points
        when curr_phase = 3 and p.match_id >= 89 and p.match_id <= 96 then p.points
        when curr_phase = 4 and p.match_id >= 97 and p.match_id <= 100 then p.points
        when curr_phase = 5 and p.match_id >= 101 and p.match_id <= 102 then p.points
        when curr_phase = 6 and p.match_id >= 103 and p.match_id <= 104 then p.points
        else 0
      end), 0) + coalesce(t.trivia_pts, 0)
    )::bigint as total_points,
    sum(case 
      when curr_phase = 1 and p.match_id >= 1 and p.match_id <= 72 then 1
      when curr_phase = 2 and p.match_id >= 73 and p.match_id <= 88 then 1
      when curr_phase = 3 and p.match_id >= 89 and p.match_id <= 96 then 1
      when curr_phase = 4 and p.match_id >= 97 and p.match_id <= 100 then 1
      when curr_phase = 5 and p.match_id >= 101 and p.match_id <= 102 then 1
      when curr_phase = 6 and p.match_id >= 103 and p.match_id <= 104 then 1
      else 0
    end)::bigint as predictions_count
  from auth.users u
  left join public.predictions p on u.id = p.user_id
  left join (
    select 
      ta.user_id,
      sum(ta.points)::bigint as trivia_pts
    from public.trivia_answers ta
    inner join public.trivia_questions tq on ta.question_id = tq.id
    where 
      (curr_phase = 1 and tq.trivia_date <= '2026-06-27') or
      (curr_phase = 2 and tq.trivia_date >= '2026-06-28' and tq.trivia_date <= '2026-07-03') or
      (curr_phase = 3 and tq.trivia_date >= '2026-07-04' and tq.trivia_date <= '2026-07-07') or
      (curr_phase = 4 and tq.trivia_date >= '2026-07-08' and tq.trivia_date <= '2026-07-12') or
      (curr_phase = 5 and tq.trivia_date >= '2026-07-13' and tq.trivia_date <= '2026-07-15') or
      (curr_phase = 6 and tq.trivia_date >= '2026-07-16')
    group by ta.user_id
  ) t on u.id = t.user_id
  where u.email like '%@quiniela.local' and u.email != 'admin@quiniela.local'
  group by u.email, t.trivia_pts
  order by total_points desc, predictions_count desc, username asc;
end;
$$;

-- Function to safely delete dummy users and demo test matches
create or replace function public.delete_dummies_and_tests()
returns text
language plpgsql
security definer
as $$
declare
  deleted_users_count int := 0;
  deleted_matches_count int := 0;
begin
  -- 1. Delete predictions for dummy users first (prevents foreign key violation)
  delete from public.predictions
  where user_id in (
    select id from auth.users
    where email in (
      'dummy@quiniela.local',
      'dummy_juan@quiniela.local',
      'dummy_sofia@quiniela.local',
      'dummy_diego@quiniela.local',
      'dummy_lucia@quiniela.local',
      'dummy_carlos@quiniela.local'
    )
  );

  -- 2. Delete predictions for demo/test matches first (prevents foreign key violation)
  delete from public.predictions
  where match_id in (
    select id from public.matches
    where home_team like 'Demo-%' or match_date < '2026-06-11 00:00:00+00'
  );

  -- 3. Delete dummy users from auth.users
  delete from auth.users
  where email in (
    'dummy@quiniela.local',
    'dummy_juan@quiniela.local',
    'dummy_sofia@quiniela.local',
    'dummy_diego@quiniela.local',
    'dummy_lucia@quiniela.local',
    'dummy_carlos@quiniela.local'
  );
  get diagnostics deleted_users_count = row_count;

  -- 4. Delete demo/test matches
  delete from public.matches
  where home_team like 'Demo-%' or match_date < '2026-06-11 00:00:00+00';
  get diagnostics deleted_matches_count = row_count;

  return '¡Dummies y partidos de prueba eliminados! Usuarios eliminados: ' || deleted_users_count || ', Partidos demo y pruebas eliminados: ' || deleted_matches_count || '.';
end;
$$;

-- Function to handle automated classification and tournament bracket propagation
create or replace function public.propagate_bracket()
returns trigger
security definer
language plpgsql
as $$
declare
  is_group_stage_done boolean;
  match_rec record;
  winner_name text;
  loser_name text;
  
  g_name text;
  g_idx int;
  standing_rec record;
  third_rec record;
  matched_match_id bigint;
begin
  -- 1. Knockout Winner/Loser Propagation (Match ID >= 73)
  -- Triggered when a knockout match score is saved and status becomes 'finished'
  if (new.status = 'finished' and old.status is distinct from 'finished' and new.id >= 73) or
     (new.status = 'finished' and (old.home_score is distinct from new.home_score or old.away_score is distinct from new.away_score) and new.id >= 73) then
     
    if new.home_score > new.away_score then
      winner_name := new.home_team;
      loser_name := new.away_team;
    elsif new.away_score > new.home_score then
      winner_name := new.away_team;
      loser_name := new.home_team;
    else
      -- Fallback for draws (should not happen in knockouts, but if it does, home advances)
      winner_name := new.home_team;
      loser_name := new.away_team;
    end if;

    -- Replace 'Ganador Partido [ID]' or 'W[ID]' with winner_name
    update public.matches
    set home_team = replace(replace(home_team, 'Ganador Partido ' || new.id, winner_name), 'W' || new.id, winner_name),
        away_team = replace(replace(away_team, 'Ganador Partido ' || new.id, winner_name), 'W' || new.id, winner_name)
    where home_team like '%Ganador Partido ' || new.id || '%'
       or away_team like '%Ganador Partido ' || new.id || '%'
       or home_team like '%W' || new.id || '%'
       or away_team like '%W' || new.id || '%';

    -- Replace 'Perdedor Partido [ID]' or 'L[ID]' with loser_name (for 3rd place match)
    update public.matches
    set home_team = replace(replace(home_team, 'Perdedor Partido ' || new.id, loser_name), 'L' || new.id, loser_name),
        away_team = replace(replace(away_team, 'Perdedor Partido ' || new.id, loser_name), 'L' || new.id, loser_name)
    where home_team like '%Perdedor Partido ' || new.id || '%'
       or away_team like '%Perdedor Partido ' || new.id || '%'
       or home_team like '%L' || new.id || '%'
       or away_team like '%L' || new.id || '%';
  end if;

  -- 2. Group Stage Standings Propagation (Group Stage Matches 1 to 72)
  -- When any group stage match transitions to finished, check if ALL 72 group stage matches are finished.
  if (new.id <= 72 and new.status = 'finished') then
    select count(*) = 0 into is_group_stage_done
    from public.matches
    where id <= 72 and status != 'finished';

    if is_group_stage_done then
      -- Create temporary table for group standings computation
      create temp table if not exists group_standings (
        team text primary key,
        grp text,
        points int default 0,
        goal_diff int default 0,
        goals_for int default 0
      ) on commit drop;
      
      truncate table group_standings;

      -- Insert all teams from group stage matches
      insert into group_standings (team, grp)
      select distinct home_team, stage_group
      from public.matches
      where id <= 72;

      -- Calculate points and goals
      for match_rec in select home_team, away_team, home_score, away_score from public.matches where id <= 72 and status = 'finished' loop
        update group_standings
        set goals_for = goals_for + match_rec.home_score,
            goal_diff = goal_diff + (match_rec.home_score - match_rec.away_score),
            points = points + case 
              when match_rec.home_score > match_rec.away_score then 3
              when match_rec.home_score = match_rec.away_score then 1
              else 0
            end
        where team = match_rec.home_team;

        update group_standings
        set goals_for = goals_for + match_rec.away_score,
            goal_diff = goal_diff + (match_rec.away_score - match_rec.home_score),
            points = points + case 
              when match_rec.away_score > match_rec.home_score then 3
              when match_rec.away_score = match_rec.home_score then 1
              else 0
            end
        where team = match_rec.away_team;
      end loop;

      -- Iterate over each group to rank teams and propagate 1st/2nd place qualifiers
      for g_name in select distinct grp from group_standings loop
        g_idx := 1;
        declare
          group_letter text := split_part(g_name, ' ', 2);
        begin
          for standing_rec in 
            select team 
            from group_standings 
            where grp = g_name 
            order by points desc, goal_diff desc, goals_for desc 
          loop
            if g_idx = 1 then
              update public.matches
              set home_team = replace(replace(home_team, '1º ' || g_name, standing_rec.team), '1' || group_letter, standing_rec.team),
                  away_team = replace(replace(away_team, '1º ' || g_name, standing_rec.team), '1' || group_letter, standing_rec.team)
              where home_team like '%1º ' || g_name || '%' or away_team like '%1º ' || g_name || '%'
                 or home_team = '1' || group_letter or away_team = '1' || group_letter;
            elsif g_idx = 2 then
              update public.matches
              set home_team = replace(replace(home_team, '2º ' || g_name, standing_rec.team), '2' || group_letter, standing_rec.team),
                  away_team = replace(replace(away_team, '2º ' || g_name, standing_rec.team), '2' || group_letter, standing_rec.team)
              where home_team like '%2º ' || g_name || '%' or away_team like '%2º ' || g_name || '%'
                 or home_team = '2' || group_letter or away_team = '2' || group_letter;
            end if;

            g_idx := g_idx + 1;
          end loop;
        end;
      end loop;

      -- Rank the 12 third-place teams to find the best 8 qualifiers
      create temp table if not exists third_places (
        team text primary key,
        grp text,
        points int,
        goal_diff int,
        goals_for int
      ) on commit drop;

      truncate table third_places;

      for g_name in select distinct grp from group_standings loop
        insert into third_places (team, grp, points, goal_diff, goals_for)
        select team, grp, points, goal_diff, goals_for
        from (
          select team, grp, points, goal_diff, goals_for,
                 row_number() over (order by points desc, goal_diff desc, goals_for desc) as rank
          from group_standings
          where grp = g_name
        ) r
        where rank = 3;
      end loop;

      -- Assign the top 8 third-place teams to the 8 matches expecting them
      for third_rec in 
        select team, grp 
        from third_places 
        order by points desc, goal_diff desc, goals_for desc 
        limit 8
      loop
        declare
          group_letter text := split_part(third_rec.grp, ' ', 2);
        begin
          -- Locate the first unassigned slot expecting this third place team group letter
          select id into matched_match_id
          from public.matches
          where id >= 73 and id <= 88
            and (
              (home_team like '3º Grupo%' and home_team like '%' || group_letter || '%') or
              (away_team like '3º Grupo%' and away_team like '%' || group_letter || '%') or
              (home_team like '3%' and home_team like '%' || group_letter || '%') or
              (away_team like '3%' and away_team like '%' || group_letter || '%')
            )
          order by id asc
          limit 1;

          if matched_match_id is not null then
            update public.matches
            set home_team = case 
                  when home_team like '3º Grupo%' and home_team like '%' || group_letter || '%' then third_rec.team 
                  when home_team like '3%' and home_team like '%' || group_letter || '%' then third_rec.team 
                  else home_team 
                end,
                away_team = case 
                  when away_team like '3º Grupo%' and away_team like '%' || group_letter || '%' then third_rec.team 
                  when away_team like '3%' and away_team like '%' || group_letter || '%' then third_rec.team 
                  else away_team 
                end
            where id = matched_match_id;
          end if;
        end;
      end loop;

    end if;
  end if;

  return new;
end;
$$;

-- Trigger to execute bracket propagation logic after a match is updated
drop trigger if exists trigger_propagate_bracket on public.matches;
create trigger trigger_propagate_bracket
after update on public.matches
for each row
execute procedure public.propagate_bracket();

-- ==========================================
-- ADMIN AND ANALYTICS FEATURES
-- ==========================================

-- 1. User Logins Table for Activity Tracking
create table if not exists public.user_logins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  login_date date not null default current_date
);

-- Ensure a user is only logged once per day for graphing active users count
create unique index if not exists user_logins_user_date_unique on public.user_logins (user_id, login_date);

-- Enable RLS for user_logins
alter table public.user_logins enable row level security;

-- RLS Policies for user_logins
drop policy if exists user_logins_insert_own on public.user_logins;
create policy user_logins_insert_own on public.user_logins
  for insert
  with check (auth.uid() = user_id);

drop policy if exists user_logins_update_own on public.user_logins;
create policy user_logins_update_own on public.user_logins
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists user_logins_select_own on public.user_logins;
create policy user_logins_select_own on public.user_logins
  for select
  using (auth.uid() = user_id);

drop policy if exists user_logins_select_admin on public.user_logins;
create policy user_logins_select_admin on public.user_logins
  for select
  using (auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- 2. Function to list all users with metadata (excl. admin)
create or replace function public.admin_get_users()
returns table(id uuid, email varchar, created_at timestamptz, last_sign_in_at timestamptz)
language plpgsql
security definer
as $$
begin
  -- Validate that requester is admin
  if auth.jwt() ->> 'email' != 'admin@quiniela.local' then
    raise exception 'Acceso denegado. Solo administradores.';
  end if;

  return query
  select u.id, u.email, u.created_at, u.last_sign_in_at
  from auth.users u
  where u.email != 'admin@quiniela.local'
  order by u.created_at desc;
end;
$$;

-- 3. Function to change a user's password securely (uses pgcrypto)
create or replace function public.admin_reset_user_password(target_user_id uuid, new_password text)
returns text
language plpgsql
security definer
as $$
begin
  -- Validate that requester is admin
  if auth.jwt() ->> 'email' != 'admin@quiniela.local' then
    raise exception 'Acceso denegado. Solo administradores.';
  end if;

  -- Ensure password is not empty or too short
  if length(new_password) < 6 then
    raise exception 'La contraseña debe tener al menos 6 caracteres.';
  end if;

  -- Update encrypted password hash in auth.users
  update auth.users
  set encrypted_password = crypt(new_password, gen_salt('bf'))
  where id = target_user_id;

  return 'Contraseña actualizada correctamente para el usuario.';
end;
$$;

-- 4. Function to delete a user securely
create or replace function public.admin_delete_user(target_user_id uuid)
returns text
language plpgsql
security definer
as $$
declare
  deleted_username text;
begin
  -- Validate that requester is admin
  if auth.jwt() ->> 'email' != 'admin@quiniela.local' then
    raise exception 'Acceso denegado. Solo administradores.';
  end if;

  -- Get email for return message
  select email into deleted_username from auth.users where id = target_user_id;

  -- Delete from auth.users (cascades to public.predictions and user_logins)
  delete from auth.users where id = target_user_id;

  return 'Usuario ' || coalesce(deleted_username, '') || ' eliminado exitosamente.';
end;
$$;

-- 5. Function to fetch daily login counts for the last 14 days
create or replace function public.admin_get_login_stats()
returns table(login_day date, active_users bigint)
language plpgsql
security definer
as $$
begin
  -- Validate that requester is admin
  if auth.jwt() ->> 'email' != 'admin@quiniela.local' then
    raise exception 'Acceso denegado. Solo administradores.';
  end if;

  return query
  select d.login_date::date, count(d.user_id)::bigint
  from public.user_logins d
  where d.login_date >= current_date - interval '13 days'
  group by d.login_date
  order by d.login_date asc;
end;
$$;

-- 6. Function to get recovery email for password reset
create or replace function public.get_user_recovery_email(target_username text)
returns text
language plpgsql
security definer
as $$
declare
  recovery_email text;
begin
  select u.raw_user_meta_data ->> 'recovery_email'
  into recovery_email
  from auth.users u
  where u.email = target_username || '@quiniela.local';

  -- Only return if it's a valid external email
  if recovery_email is null or recovery_email = '' then
    return null;
  end if;

  return recovery_email;
end;
$$;


-- ==========================================
-- WORLD CUP EMULATION & PHASE LEADERBOARD
-- ==========================================

-- Function to reset the World Cup emulation back to initial state
create or replace function public.reset_world_cup_emulation()
returns text
language plpgsql
security definer
as $$
begin
  -- Validate that requester is admin
  if auth.jwt() ->> 'email' != 'admin@quiniela.local' then
    raise exception 'Acceso denegado. Solo administradores.';
  end if;

  -- 1. Delete all predictions
  delete from public.predictions where id is not null;

  -- 2. Reset all matches: clear scores and set status to pending
  update public.matches
  set home_score = null,
      away_score = null,
      status = 'pending'
  where id is not null;

  -- 3. Restore original placeholder teams for knockout matches (73-104)
  update public.matches set home_team = '2º Grupo A', away_team = '2º Grupo B' where id = 73;
  update public.matches set home_team = '1º Grupo E', away_team = '3º Grupo A/B/C/D/F' where id = 74;
  update public.matches set home_team = '1º Grupo F', away_team = '2º Grupo C' where id = 75;
  update public.matches set home_team = '1º Grupo C', away_team = '2º Grupo F' where id = 76;
  update public.matches set home_team = '1º Grupo I', away_team = '3º Grupo C/D/F/G/H' where id = 77;
  update public.matches set home_team = '2º Grupo E', away_team = '2º Grupo I' where id = 78;
  update public.matches set home_team = '1º Grupo A', away_team = '3º Grupo C/E/F/H/I' where id = 79;
  update public.matches set home_team = '1º Grupo L', away_team = '3º Grupo E/H/I/J/K' where id = 80;
  update public.matches set home_team = '1º Grupo D', away_team = '3º Grupo B/E/F/I/J' where id = 81;
  update public.matches set home_team = '1º Grupo G', away_team = '3º Grupo A/E/H/I/J' where id = 82;
  update public.matches set home_team = '2º Grupo K', away_team = '2º Grupo L' where id = 83;
  update public.matches set home_team = '1º Grupo H', away_team = '2º Grupo J' where id = 84;
  update public.matches set home_team = '1º Grupo B', away_team = '3º Grupo E/F/G/I/J' where id = 85;
  update public.matches set home_team = '1º Grupo J', away_team = '2º Grupo H' where id = 86;
  update public.matches set home_team = '1º Grupo K', away_team = '3º Grupo D/E/I/J/L' where id = 87;
  update public.matches set home_team = '2º Grupo D', away_team = '2º Grupo G' where id = 88;
  update public.matches set home_team = 'Ganador Partido 74', away_team = 'Ganador Partido 77' where id = 89;
  update public.matches set home_team = 'Ganador Partido 73', away_team = 'Ganador Partido 75' where id = 90;
  update public.matches set home_team = 'Ganador Partido 76', away_team = 'Ganador Partido 78' where id = 91;
  update public.matches set home_team = 'Ganador Partido 79', away_team = 'Ganador Partido 80' where id = 92;
  update public.matches set home_team = 'Ganador Partido 83', away_team = 'Ganador Partido 84' where id = 93;
  update public.matches set home_team = 'Ganador Partido 81', away_team = 'Ganador Partido 82' where id = 94;
  update public.matches set home_team = 'Ganador Partido 86', away_team = 'Ganador Partido 88' where id = 95;
  update public.matches set home_team = 'Ganador Partido 85', away_team = 'Ganador Partido 87' where id = 96;
  update public.matches set home_team = 'Ganador Partido 89', away_team = 'Ganador Partido 90' where id = 97;
  update public.matches set home_team = 'Ganador Partido 93', away_team = 'Ganador Partido 94' where id = 98;
  update public.matches set home_team = 'Ganador Partido 91', away_team = 'Ganador Partido 92' where id = 99;
  update public.matches set home_team = 'Ganador Partido 95', away_team = 'Ganador Partido 96' where id = 100;
  update public.matches set home_team = 'Ganador Partido 97', away_team = 'Ganador Partido 98' where id = 101;
  update public.matches set home_team = 'Ganador Partido 99', away_team = 'Ganador Partido 100' where id = 102;
  update public.matches set home_team = 'Perdedor Partido 101', away_team = 'Perdedor Partido 102' where id = 103;
  update public.matches set home_team = 'Ganador Partido 101', away_team = 'Ganador Partido 102' where id = 104;

  return '¡Emulación del Mundial reiniciada! Todos los partidos vuelven a estado pendiente y las predicciones fueron eliminadas.';
end;
$$;

-- Function to emulate the entire World Cup phase by phase
create or replace function public.emulate_world_cup()
returns text
language plpgsql
security definer
as $$
declare
  m_id int;
  p_home int;
  p_away int;
  res text;
begin
  -- Validate that requester is admin
  if auth.jwt() ->> 'email' != 'admin@quiniela.local' then
    raise exception 'Acceso denegado. Solo administradores.';
  end if;

  -- 1. Reset all matches status and scores
  update public.matches
  set home_score = null,
      away_score = null,
      status = 'pending'
  where id is not null;

  -- 2. Restore original teams for matches 73 to 104
  update public.matches set home_team = '2º Grupo A', away_team = '2º Grupo B' where id = 73;
  update public.matches set home_team = '1º Grupo E', away_team = '3º Grupo A/B/C/D/F' where id = 74;
  update public.matches set home_team = '1º Grupo F', away_team = '2º Grupo C' where id = 75;
  update public.matches set home_team = '1º Grupo C', away_team = '2º Grupo F' where id = 76;
  update public.matches set home_team = '1º Grupo I', away_team = '3º Grupo C/D/F/G/H' where id = 77;
  update public.matches set home_team = '2º Grupo E', away_team = '2º Grupo I' where id = 78;
  update public.matches set home_team = '1º Grupo A', away_team = '3º Grupo C/E/F/H/I' where id = 79;
  update public.matches set home_team = '1º Grupo L', away_team = '3º Grupo E/H/I/J/K' where id = 80;
  update public.matches set home_team = '1º Grupo D', away_team = '3º Grupo B/E/F/I/J' where id = 81;
  update public.matches set home_team = '1º Grupo G', away_team = '3º Grupo A/E/H/I/J' where id = 82;
  update public.matches set home_team = '2º Grupo K', away_team = '2º Grupo L' where id = 83;
  update public.matches set home_team = '1º Grupo H', away_team = '2º Grupo J' where id = 84;
  update public.matches set home_team = '1º Grupo B', away_team = '3º Grupo E/F/G/I/J' where id = 85;
  update public.matches set home_team = '1º Grupo J', away_team = '2º Grupo H' where id = 86;
  update public.matches set home_team = '1º Grupo K', away_team = '3º Grupo D/E/I/J/L' where id = 87;
  update public.matches set home_team = '2º Grupo D', away_team = '2º Grupo G' where id = 88;
  update public.matches set home_team = 'Ganador Partido 74', away_team = 'Ganador Partido 77' where id = 89;
  update public.matches set home_team = 'Ganador Partido 73', away_team = 'Ganador Partido 75' where id = 90;
  update public.matches set home_team = 'Ganador Partido 76', away_team = 'Ganador Partido 78' where id = 91;
  update public.matches set home_team = 'Ganador Partido 79', away_team = 'Ganador Partido 80' where id = 92;
  update public.matches set home_team = 'Ganador Partido 83', away_team = 'Ganador Partido 84' where id = 93;
  update public.matches set home_team = 'Ganador Partido 81', away_team = 'Ganador Partido 82' where id = 94;
  update public.matches set home_team = 'Ganador Partido 86', away_team = 'Ganador Partido 88' where id = 95;
  update public.matches set home_team = 'Ganador Partido 85', away_team = 'Ganador Partido 87' where id = 96;
  update public.matches set home_team = 'Ganador Partido 89', away_team = 'Ganador Partido 90' where id = 97;
  update public.matches set home_team = 'Ganador Partido 93', away_team = 'Ganador Partido 94' where id = 98;
  update public.matches set home_team = 'Ganador Partido 91', away_team = 'Ganador Partido 92' where id = 99;
  update public.matches set home_team = 'Ganador Partido 95', away_team = 'Ganador Partido 96' where id = 100;
  update public.matches set home_team = 'Ganador Partido 97', away_team = 'Ganador Partido 98' where id = 101;
  update public.matches set home_team = 'Ganador Partido 99', away_team = 'Ganador Partido 100' where id = 102;
  update public.matches set home_team = 'Perdedor Partido 101', away_team = 'Perdedor Partido 102' where id = 103;
  update public.matches set home_team = 'Ganador Partido 101', away_team = 'Ganador Partido 102' where id = 104;

  -- 3. Seed dummy users and predictions
  res := public.seed_dummies_and_predictions();

  -- 4. Emulate Phase 1: Group Stage (matches 1..72)
  for m_id in 1..72 loop
    p_home := floor(random() * 5);
    p_away := floor(random() * 5);
    update public.matches
    set home_score = p_home,
        away_score = p_away,
        status = 'finished'
    where id = m_id;
  end loop;

  -- 5. Emulate Phase 2: Round of 32 (matches 73..88)
  for m_id in 73..88 loop
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    if p_home = p_away then
      p_home := p_home + 1;
    end if;
    update public.matches
    set home_score = p_home,
        away_score = p_away,
        status = 'finished'
    where id = m_id;
  end loop;

  -- 6. Emulate Phase 3: Round of 16 (matches 89..96)
  for m_id in 89..96 loop
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    if p_home = p_away then
      p_home := p_home + 1;
    end if;
    update public.matches
    set home_score = p_home,
        away_score = p_away,
        status = 'finished'
    where id = m_id;
  end loop;

  -- 7. Emulate Phase 4: Quarterfinals (matches 97..100)
  for m_id in 97..100 loop
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    if p_home = p_away then
      p_home := p_home + 1;
    end if;
    update public.matches
    set home_score = p_home,
        away_score = p_away,
        status = 'finished'
    where id = m_id;
  end loop;

  -- 8. Emulate Phase 5: Semifinals (matches 101..102)
  for m_id in 101..102 loop
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    if p_home = p_away then
      p_home := p_home + 1;
    end if;
    update public.matches
    set home_score = p_home,
        away_score = p_away,
        status = 'finished'
    where id = m_id;
  end loop;

  -- 9. Emulate Phase 6: Third Place and Final (matches 103..104)
  for m_id in 103..104 loop
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    if p_home = p_away then
      p_home := p_home + 1;
    end if;
    update public.matches
    set home_score = p_home,
        away_score = p_away,
        status = 'finished'
    where id = m_id;
  end loop;

  return '¡Emulación completa del Mundial finalizada con éxito! Todos los partidos han sido jugados y los puntos de las predicciones de los 5 usuarios dummy calculados.';
end;
$$;

-- Function to compute leaderboard by phase
create or replace function public.get_leaderboard_by_phase()
returns table(
  username text,
  fase1 bigint,
  fase2 bigint,
  fase3 bigint,
  fase4 bigint,
  fase5 bigint,
  fase6 bigint,
  total_points bigint
)
language plpgsql
security definer
as $$
begin
  return query
  select
    split_part(u.email, '@', 1)::text as username,
    (coalesce(sum(case when p.match_id >= 1 and p.match_id <= 72 then p.points else 0 end), 0) + coalesce(t.fase1_trivia, 0))::bigint as fase1,
    (coalesce(sum(case when p.match_id >= 73 and p.match_id <= 88 then p.points else 0 end), 0) + coalesce(t.fase2_trivia, 0))::bigint as fase2,
    (coalesce(sum(case when p.match_id >= 89 and p.match_id <= 96 then p.points else 0 end), 0) + coalesce(t.fase3_trivia, 0))::bigint as fase3,
    (coalesce(sum(case when p.match_id >= 97 and p.match_id <= 100 then p.points else 0 end), 0) + coalesce(t.fase4_trivia, 0))::bigint as fase4,
    (coalesce(sum(case when p.match_id >= 101 and p.match_id <= 102 then p.points else 0 end), 0) + coalesce(t.fase5_trivia, 0))::bigint as fase5,
    (coalesce(sum(case when p.match_id >= 103 and p.match_id <= 104 then p.points else 0 end), 0) + coalesce(t.fase6_trivia, 0))::bigint as fase6,
    (coalesce(sum(p.points), 0) + coalesce(t.total_trivia, 0))::bigint as total_points
  from auth.users u
  left join public.predictions p on u.id = p.user_id
  left join (
    select
      ta.user_id,
      coalesce(sum(case when tq.trivia_date <= '2026-06-27' then ta.points else 0 end), 0)::bigint as fase1_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-06-28' and tq.trivia_date <= '2026-07-03' then ta.points else 0 end), 0)::bigint as fase2_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-04' and tq.trivia_date <= '2026-07-07' then ta.points else 0 end), 0)::bigint as fase3_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-08' and tq.trivia_date <= '2026-07-12' then ta.points else 0 end), 0)::bigint as fase4_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-13' and tq.trivia_date <= '2026-07-15' then ta.points else 0 end), 0)::bigint as fase5_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-16' then ta.points else 0 end), 0)::bigint as fase6_trivia,
      coalesce(sum(ta.points), 0)::bigint as total_trivia
    from public.trivia_answers ta
    inner join public.trivia_questions tq on ta.question_id = tq.id
    group by ta.user_id
  ) t on u.id = t.user_id
  where u.email like '%@quiniela.local' and u.email != 'admin@quiniela.local'
  group by u.email, t.fase1_trivia, t.fase2_trivia, t.fase3_trivia, t.fase4_trivia, t.fase5_trivia, t.fase6_trivia, t.total_trivia
  order by total_points desc, username asc;
end;
$$;


