-- =====================================================================
-- QUINIELA MUNDIAL - CONSOLIDATED DATABASE SETUP & MATCH SEEDING
-- Run this script in your Supabase SQL Editor (https://supabase.com)
-- =====================================================================

-- 1. Update matches table structure (adds missing columns stage_group, venue, and score_manually_set)
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS stage_group text;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS venue text;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS score_manually_set boolean not null default false;

-- 2. Ensure predictions table and indexes are set up
CREATE TABLE IF NOT EXISTS public.predictions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  match_id bigint NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  predicted_home int NOT NULL,
  predicted_away int NOT NULL,
  points int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS predictions_user_match_unique ON public.predictions (user_id, match_id);
CREATE INDEX IF NOT EXISTS predictions_match_id_idx ON public.predictions (match_id);

-- Enable RLS
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;

-- Matches RLS policies
DROP POLICY IF EXISTS public_matches_select ON public.matches;
CREATE POLICY public_matches_select ON public.matches FOR SELECT USING (true);

DROP POLICY IF EXISTS matches_insert_auth ON public.matches;
CREATE POLICY matches_insert_auth ON public.matches FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = 'admin@quiniela.local');

DROP POLICY IF EXISTS matches_update_auth ON public.matches;
CREATE POLICY matches_update_auth ON public.matches FOR UPDATE USING (auth.jwt() ->> 'email' = 'admin@quiniela.local') WITH CHECK (auth.jwt() ->> 'email' = 'admin@quiniela.local');

DROP POLICY IF EXISTS matches_delete_auth ON public.matches;
CREATE POLICY matches_delete_auth ON public.matches FOR DELETE USING (auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- Predictions RLS policies
DROP POLICY IF EXISTS predictions_select_public ON public.predictions;
CREATE POLICY predictions_select_public ON public.predictions FOR SELECT USING (true);

DROP POLICY IF EXISTS predictions_insert_own ON public.predictions;
CREATE POLICY predictions_insert_own ON public.predictions FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS predictions_update_own ON public.predictions;
CREATE POLICY predictions_update_own ON public.predictions FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS predictions_delete_own ON public.predictions;
CREATE POLICY predictions_delete_own ON public.predictions FOR DELETE USING (auth.uid() = user_id);

-- 3. Setup Triggers and scoring functions
CREATE OR REPLACE FUNCTION public.update_prediction_points()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (new.status = 'finished') AND 
     (old.status IS DISTINCT FROM 'finished' OR 
      old.home_score IS DISTINCT FROM new.home_score OR 
      old.away_score IS DISTINCT FROM new.away_score) THEN
    
    UPDATE public.predictions p
    SET points = CASE
      WHEN new.home_score = p.predicted_home AND new.away_score = p.predicted_away THEN 5
      WHEN sign(new.home_score - new.away_score) = sign(p.predicted_home - p.predicted_away) THEN
        CASE
          WHEN new.home_score = new.away_score THEN 1
          ELSE 3
        END
      ELSE 0
    END
    WHERE p.match_id = new.id;
  ELSIF (new.status = 'pending' AND old.status = 'finished') THEN
    UPDATE public.predictions p
    SET points = 0
    WHERE p.match_id = new.id;
  END IF;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trigger_update_prediction_points ON public.matches;
CREATE TRIGGER trigger_update_prediction_points
AFTER UPDATE ON public.matches
FOR EACH ROW
EXECUTE PROCEDURE public.update_prediction_points();

CREATE OR REPLACE FUNCTION public.check_prediction_lock()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  match_kickoff timestamptz;
BEGIN
  IF current_setting('my.seeding_mode', true) = 'on' THEN
    RETURN new;
  END IF;

  IF (TG_OP = 'UPDATE') AND 
     (old.predicted_home = new.predicted_home) AND 
     (old.predicted_away = new.predicted_away) THEN
    RETURN new;
  END IF;

  SELECT match_date INTO match_kickoff FROM public.matches WHERE id = new.match_id;
  
  IF match_kickoff IS NULL THEN
    RAISE EXCEPTION 'Match not found';
  END IF;
  
  IF now() >= match_kickoff - interval '1 hour' THEN
    RAISE EXCEPTION 'Predictions are locked for this match.';
  END IF;
  
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trigger_check_prediction_lock ON public.predictions;
CREATE TRIGGER trigger_check_prediction_lock
BEFORE INSERT OR UPDATE ON public.predictions
FOR EACH ROW
EXECUTE PROCEDURE public.check_prediction_lock();

-- 4. User Logins Table and RLS
CREATE TABLE IF NOT EXISTS public.user_logins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  login_date date NOT NULL DEFAULT current_date
);

CREATE UNIQUE INDEX IF NOT EXISTS user_logins_user_date_unique ON public.user_logins (user_id, login_date);

ALTER TABLE public.user_logins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_logins_insert_own ON public.user_logins;
CREATE POLICY user_logins_insert_own ON public.user_logins FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_logins_update_own ON public.user_logins;
CREATE POLICY user_logins_update_own ON public.user_logins FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_logins_select_own ON public.user_logins;
CREATE POLICY user_logins_select_own ON public.user_logins FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS user_logins_select_admin ON public.user_logins;
CREATE POLICY user_logins_select_admin ON public.user_logins FOR SELECT USING (auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- 5. Admin and Analytics RPC Functions
CREATE OR REPLACE FUNCTION public.admin_get_users()
RETURNS table(id uuid, email varchar, created_at timestamptz, last_sign_in_at timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  RETURN QUERY
  SELECT u.id, u.email, u.created_at, u.last_sign_in_at
  FROM auth.users u
  WHERE u.email != 'admin@quiniela.local'
  ORDER BY u.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_reset_user_password(target_user_id uuid, new_password text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  IF length(new_password) < 6 THEN
    RAISE EXCEPTION 'La contraseña debe tener al menos 6 caracteres.';
  END IF;

  UPDATE auth.users
  SET encrypted_password = crypt(new_password, gen_salt('bf'))
  where id = target_user_id;

  RETURN 'Contraseña actualizada correctamente para el usuario.';
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_user(target_user_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  deleted_username text;
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  SELECT email INTO deleted_username FROM auth.users WHERE id = target_user_id;

  DELETE FROM auth.users WHERE id = target_user_id;

  RETURN 'Usuario ' || coalesce(deleted_username, '') || ' eliminado exitosamente.';
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_get_login_stats()
RETURNS table(login_day date, active_users bigint)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  RETURN QUERY
  SELECT d.login_date::date, count(d.user_id)::bigint
  FROM public.user_logins d
  WHERE d.login_date >= current_date - interval '13 days'
  GROUP BY d.login_date
  ORDER BY d.login_date ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_reset_database()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  TRUNCATE TABLE public.matches CASCADE;
  TRUNCATE TABLE public.user_logins CASCADE;

  DELETE FROM auth.users WHERE email != 'admin@quiniela.local';

  RETURN '¡Base de datos reiniciada con éxito! Todos los partidos, pronósticos y usuarios (excepto el administrador) han sido eliminados de forma permanente.';
END;
$$;

CREATE OR REPLACE FUNCTION public.get_leaderboard()
RETURNS table(username text, total_points bigint, predictions_count bigint)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    split_part(u.email, '@', 1)::text as username,
    coalesce(sum(p.points), 0)::bigint as total_points,
    count(p.id)::bigint as predictions_count
  from auth.users u
  left join public.predictions p on u.id = p.user_id
  where u.email like '%@quiniela.local' and u.email != 'admin@quiniela.local'
  group by u.email
  order by total_points desc, predictions_count desc;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_dummies_and_tests()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  deleted_users_count int := 0;
  deleted_matches_count int := 0;
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  DELETE FROM public.predictions
  WHERE user_id in (
    SELECT id FROM auth.users
    WHERE email in (
      'dummy@quiniela.local',
      'dummy_juan@quiniela.local',
      'dummy_sofia@quiniela.local',
      'dummy_diego@quiniela.local',
      'dummy_lucia@quiniela.local',
      'dummy_carlos@quiniela.local'
    )
  );

  DELETE FROM public.predictions
  where match_id in (
    SELECT id FROM public.matches
    where home_team like 'Demo-%' or match_date < '2026-06-11 00:00:00+00'
  );

  DELETE FROM auth.users
  where email in (
    'dummy@quiniela.local',
    'dummy_juan@quiniela.local',
    'dummy_sofia@quiniela.local',
    'dummy_diego@quiniela.local',
    'dummy_lucia@quiniela.local',
    'dummy_carlos@quiniela.local'
  );
  GET DIAGNOSTICS deleted_users_count = row_count;

  DELETE FROM public.matches
  where home_team like 'Demo-%' or match_date < '2026-06-11 00:00:00+00';
  GET DIAGNOSTICS deleted_matches_count = row_count;

  RETURN '¡Dummies y partidos de prueba eliminados! Usuarios eliminados: ' || deleted_users_count || ', Partidos demo y pruebas eliminados: ' || deleted_matches_count || '.';
END;
$$;

CREATE OR REPLACE FUNCTION public.seed_dummies_and_predictions()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  dummy_usernames text[] := array['dummy_juan', 'dummy_sofia', 'dummy_diego', 'dummy_lucia', 'dummy_carlos'];
  d_username text;
  d_email text;
  d_id uuid;
  m_record record;
  p_home int;
  p_away int;
  created_count int := 0;
  pred_count int := 0;
BEGIN
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  PERFORM set_config('my.seeding_mode', 'on', true);

  FOREACH d_username in array dummy_usernames LOOP
    d_email := d_username || '@quiniela.local';
    
    SELECT id INTO d_id FROM auth.users where email = d_email;
    
    IF d_id IS NULL THEN
      d_id := gen_random_uuid();
      
      INSERT INTO auth.users (
        id,
        instance_id,
        email,
        encrypted_password,
        email_confirmed_at,
        raw_app_meta_data,
        raw_user_meta_data,
        created_at,
        updated_at,
        role,
        aud,
        confirmation_token
      )
      VALUES (
        d_id,
        '00000000-0000-0000-0000-000000000000',
        d_email,
        crypt('password123', gen_salt('bf')),
        now(),
        '{"provider":"email","providers":["email"]}',
        '{}',
        now(),
        now(),
        'authenticated',
        'authenticated',
        ''
      );
      
      created_count := created_count + 1;
    END IF;

    DELETE FROM public.predictions where user_id = d_id;

    FOR m_record in SELECT id, status, home_score, away_score FROM public.matches LOOP
      p_home := floor(random() * 5);
      p_away := floor(random() * 5);
      
      INSERT INTO public.predictions (user_id, match_id, predicted_home, predicted_away, points)
      VALUES (
        d_id, 
        m_record.id, 
        p_home, 
        p_away,
        CASE
          WHEN m_record.status = 'finished' THEN
            CASE
              WHEN m_record.home_score = p_home AND m_record.away_score = p_away THEN 5
              WHEN sign(m_record.home_score - m_record.away_score) = sign(p_home - p_away) THEN
                CASE
                  WHEN m_record.home_score = m_record.away_score then 1
                  ELSE 3
                END
              ELSE 0
            END
          ELSE 0
        END
      );
      
      pred_count := pred_count + 1;
    END LOOP;
  END LOOP;

  RETURN '¡Se crearon/verificaron los 5 usuarios dummy con éxito! Se registraron ' || pred_count || ' pronósticos aleatorios en total.';
END;
$$;

CREATE OR REPLACE FUNCTION public.propagate_bracket()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  is_group_stage_done boolean;
  match_rec record;
  winner_name text;
  loser_name text;
  
  g_name text;
  g_idx int;
  standing_rec record;
  third_rec record;
  matched_match_id bigint;
BEGIN
  IF (new.status = 'finished' and old.status is distinct from 'finished' and new.id >= 73) or
     (new.status = 'finished' and (old.home_score is distinct from new.home_score or old.away_score is distinct from new.away_score) and new.id >= 73) then
     
    IF new.home_score > new.away_score THEN
      winner_name := new.home_team;
      loser_name := new.away_team;
    ELSIF new.away_score > new.home_score THEN
      winner_name := new.away_team;
      loser_name := new.home_team;
    ELSE
      winner_name := new.home_team;
      loser_name := new.away_team;
    END IF;

    UPDATE public.matches
    SET home_team = replace(home_team, 'Ganador Partido ' || new.id, winner_name),
        away_team = replace(away_team, 'Ganador Partido ' || new.id, winner_name)
    where home_team like '%Ganador Partido ' || new.id || '%'
       or away_team like '%Ganador Partido ' || new.id || '%';

    UPDATE public.matches
    SET home_team = replace(home_team, 'Perdedor Partido ' || new.id, loser_name),
        away_team = replace(away_team, 'Perdedor Partido ' || new.id, loser_name)
    where home_team like '%Perdedor Partido ' || new.id || '%'
       or away_team like '%Perdedor Partido ' || new.id || '%';
  END IF;

  IF (new.id <= 72 and new.status = 'finished') THEN
    SELECT count(*) = 0 INTO is_group_stage_done
    FROM public.matches
    where id <= 72 and status != 'finished';

    IF is_group_stage_done THEN
      CREATE TEMP TABLE IF NOT EXISTS group_standings (
        team text primary key,
        grp text,
        points int default 0,
        goal_diff int default 0,
        goals_for int default 0
      ) ON COMMIT DROP;
      
      TRUNCATE TABLE group_standings;

      INSERT INTO group_standings (team, grp)
      SELECT distinct home_team, stage_group
      FROM public.matches
      where id <= 72;

      FOR match_rec in SELECT home_team, away_team, home_score, away_score FROM public.matches where id <= 72 and status = 'finished' LOOP
        UPDATE group_standings
        SET goals_for = goals_for + match_rec.home_score,
            goal_diff = goal_diff + (match_rec.home_score - match_rec.away_score),
            points = points + CASE 
              WHEN match_rec.home_score > match_rec.away_score THEN 3
              WHEN match_rec.home_score = match_rec.away_score THEN 1
              ELSE 0
            END
        where team = match_rec.home_team;

        UPDATE group_standings
        SET goals_for = goals_for + match_rec.away_score,
            goal_diff = goal_diff + (match_rec.away_score - match_rec.home_score),
            points = points + CASE 
              WHEN match_rec.away_score > match_rec.home_score THEN 3
              WHEN match_rec.away_score = match_rec.home_score THEN 1
              ELSE 0
            END
        where team = match_rec.away_team;
      END LOOP;

      FOR g_name in SELECT distinct grp FROM group_standings LOOP
        g_idx := 1;
        FOR standing_rec in 
          SELECT team 
          FROM group_standings 
          where grp = g_name 
          ORDER BY points DESC, goal_diff DESC, goals_for DESC 
        LOOP
          IF g_idx = 1 THEN
            UPDATE public.matches
            SET home_team = replace(home_team, '1º ' || g_name, standing_rec.team),
                away_team = replace(away_team, '1º ' || g_name, standing_rec.team)
            where home_team like '%1º ' || g_name || '%' or away_team like '%1º ' || g_name || '%';
          ELSIF g_idx = 2 THEN
            UPDATE public.matches
            SET home_team = replace(home_team, '2º ' || g_name, standing_rec.team),
                away_team = replace(away_team, '2º ' || g_name, standing_rec.team)
            where home_team like '%2º ' || g_name || '%' or away_team like '%2º ' || g_name || '%';
          END IF;

          g_idx := g_idx + 1;
        END LOOP;
      END LOOP;

      CREATE TEMP TABLE IF NOT EXISTS third_places (
        team text primary key,
        grp text,
        points int,
        goal_diff int,
        goals_for int
      ) ON COMMIT DROP;

      TRUNCATE TABLE third_places;

      FOR g_name in SELECT distinct grp FROM group_standings LOOP
        INSERT INTO third_places (team, grp, points, goal_diff, goals_for)
        SELECT team, grp, points, goal_diff, goals_for
        FROM (
          SELECT team, grp, points, goal_diff, goals_for,
                 row_number() over (order by points desc, goal_diff desc, goals_for desc) as rank
          FROM group_standings
          where grp = g_name
        ) r
        where rank = 3;
      END LOOP;

      FOR third_rec in 
        SELECT team, grp 
        FROM third_places 
        ORDER BY points DESC, goal_diff DESC, goals_for DESC 
        LIMIT 8
      LOOP
        DECLARE
          group_letter text := split_part(third_rec.grp, ' ', 2);
        BEGIN
          SELECT id INTO matched_match_id
          FROM public.matches
          where id >= 73 and id <= 88
            and (
              (home_team like '3º Grupo%' and home_team like '%' || group_letter || '%') or
              (away_team like '3º Grupo%' and away_team like '%' || group_letter || '%')
            )
          ORDER BY id ASC
          LIMIT 1;

          IF matched_match_id IS NOT NULL THEN
            UPDATE public.matches
            SET home_team = CASE WHEN home_team like '3º Grupo%' and home_team like '%' || group_letter || '%' THEN third_rec.team ELSE home_team END,
                away_team = CASE WHEN away_team like '3º Grupo%' and away_team like '%' || group_letter || '%' THEN third_rec.team ELSE away_team END
            where id = matched_match_id;
          END IF;
        END;
      END LOOP;

    END IF;
  END IF;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trigger_propagate_bracket ON public.matches;
CREATE TRIGGER trigger_propagate_bracket
AFTER UPDATE ON public.matches
FOR EACH ROW
EXECUTE PROCEDURE public.propagate_bracket();

-- 6. Insert matches data
TRUNCATE TABLE public.matches CASCADE;

INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (1, 'Mexico', 'South Africa', 'Grupo A', 'Mexico City', '2026-06-11T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (2, 'Korea Republic', 'Czechia', 'Grupo A', 'Guadalajara (Zapopan)', '2026-06-12T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (3, 'Czechia', 'South Africa', 'Grupo A', 'Atlanta', '2026-06-18T16:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (4, 'Mexico', 'Korea Republic', 'Grupo A', 'Guadalajara (Zapopan)', '2026-06-19T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (5, 'Czechia', 'Mexico', 'Grupo A', 'Mexico City', '2026-06-25T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (6, 'South Africa', 'Korea Republic', 'Grupo A', 'Monterrey (Guadalupe)', '2026-06-25T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (7, 'Canada', 'Bosnia and Herzegovina', 'Grupo B', 'Toronto', '2026-06-12T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (8, 'Qatar', 'Switzerland', 'Grupo B', 'San Francisco Bay Area (Santa Clara)', '2026-06-13T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (9, 'Switzerland', 'Bosnia and Herzegovina', 'Grupo B', 'Los Angeles (Inglewood)', '2026-06-18T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (10, 'Canada', 'Qatar', 'Grupo B', 'Vancouver', '2026-06-18T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (11, 'Switzerland', 'Canada', 'Grupo B', 'Vancouver', '2026-06-24T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (12, 'Bosnia and Herzegovina', 'Qatar', 'Grupo B', 'Seattle', '2026-06-24T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (13, 'Brazil', 'Morocco', 'Grupo C', 'New York/New Jersey (East Rutherford)', '2026-06-13T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (14, 'Haiti', 'Scotland', 'Grupo C', 'Boston (Foxborough)', '2026-06-14T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (15, 'Scotland', 'Morocco', 'Grupo C', 'Boston (Foxborough)', '2026-06-19T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (16, 'Brazil', 'Haiti', 'Grupo C', 'Philadelphia', '2026-06-20T00:30:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (17, 'Scotland', 'Brazil', 'Grupo C', 'Miami (Miami Gardens)', '2026-06-24T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (18, 'Morocco', 'Haiti', 'Grupo C', 'Atlanta', '2026-06-24T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (19, 'USA', 'Paraguay', 'Grupo D', 'Los Angeles (Inglewood)', '2026-06-13T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (20, 'Australia', 'Türkiye', 'Grupo D', 'Vancouver', '2026-06-14T04:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (21, 'USA', 'Australia', 'Grupo D', 'Seattle', '2026-06-19T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (22, 'Türkiye', 'Paraguay', 'Grupo D', 'San Francisco Bay Area (Santa Clara)', '2026-06-20T03:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (23, 'Türkiye', 'USA', 'Grupo D', 'Los Angeles (Inglewood)', '2026-06-26T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (24, 'Paraguay', 'Australia', 'Grupo D', 'San Francisco Bay Area (Santa Clara)', '2026-06-26T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (25, 'Germany', 'Curaçao', 'Grupo E', 'Houston', '2026-06-14T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (26, 'Côte''Ivoire', 'Ecuador', 'Grupo E', 'Philadelphia', '2026-06-14T23:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (27, 'Germany', 'Côte''Ivoire', 'Grupo E', 'Toronto', '2026-06-20T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (28, 'Ecuador', 'Curaçao', 'Grupo E', 'Kansas City', '2026-06-21T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (29, 'Curaçao', 'Côte''Ivoire', 'Grupo E', 'Philadelphia', '2026-06-25T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (30, 'Ecuador', 'Germany', 'Grupo E', 'New York/New Jersey (East Rutherford)', '2026-06-25T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (31, 'Netherlands', 'Japan', 'Grupo F', 'Dallas (Arlington)', '2026-06-14T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (32, 'Sweden', 'Tunisia', 'Grupo F', 'Monterrey (Guadalupe)', '2026-06-15T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (33, 'Netherlands', 'Sweden', 'Grupo F', 'Houston', '2026-06-20T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (34, 'Tunisia', 'Japan', 'Grupo F', 'Monterrey (Guadalupe)', '2026-06-21T04:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (35, 'Japan', 'Sweden', 'Grupo F', 'Dallas (Arlington)', '2026-06-25T23:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (36, 'Tunisia', 'Netherlands', 'Grupo F', 'Kansas City', '2026-06-25T23:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (37, 'Belgium', 'Egypt', 'Grupo G', 'Seattle', '2026-06-15T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (38, 'IR Iran', 'New Zealand', 'Grupo G', 'Los Angeles (Inglewood)', '2026-06-16T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (39, 'Belgium', 'IR Iran', 'Grupo G', 'Los Angeles (Inglewood)', '2026-06-21T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (40, 'New Zealand', 'Egypt', 'Grupo G', 'Vancouver', '2026-06-22T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (41, 'Egypt', 'IR Iran', 'Grupo G', 'Seattle', '2026-06-27T03:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (42, 'New Zealand', 'Belgium', 'Grupo G', 'Vancouver', '2026-06-27T03:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (43, 'Spain', 'Cabo Verde', 'Grupo H', 'Atlanta', '2026-06-15T16:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (44, 'Saudi Arabia', 'Uruguay', 'Grupo H', 'Miami (Miami Gardens)', '2026-06-15T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (45, 'Spain', 'Saudi Arabia', 'Grupo H', 'Atlanta', '2026-06-21T16:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (46, 'Uruguay', 'Cabo Verde', 'Grupo H', 'Miami (Miami Gardens)', '2026-06-21T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (47, 'Cabo Verde', 'Saudi Arabia', 'Grupo H', 'Houston', '2026-06-27T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (48, 'Uruguay', 'Spain', 'Grupo H', 'Guadalajara (Zapopan)', '2026-06-27T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (49, 'France', 'Senegal', 'Grupo I', 'New York/New Jersey (East Rutherford)', '2026-06-16T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (50, 'Iraq', 'Norway', 'Grupo I', 'Boston (Foxborough)', '2026-06-16T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (51, 'France', 'Iraq', 'Grupo I', 'Philadelphia', '2026-06-22T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (52, 'Norway', 'Senegal', 'Grupo I', 'New York/New Jersey (East Rutherford)', '2026-06-23T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (53, 'Norway', 'France', 'Grupo I', 'Boston (Foxborough)', '2026-06-26T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (54, 'Senegal', 'Iraq', 'Grupo I', 'Toronto', '2026-06-26T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (55, 'Argentina', 'Algeria', 'Grupo J', 'Kansas City', '2026-06-17T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (56, 'Austria', 'Jordan', 'Grupo J', 'San Francisco Bay Area (Santa Clara)', '2026-06-17T04:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (57, 'Argentina', 'Austria', 'Grupo J', 'Dallas (Arlington)', '2026-06-22T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (58, 'Jordan', 'Algeria', 'Grupo J', 'San Francisco Bay Area (Santa Clara)', '2026-06-23T03:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (59, 'Algeria', 'Austria', 'Grupo J', 'Kansas City', '2026-06-28T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (60, 'Jordan', 'Argentina', 'Grupo J', 'Dallas (Arlington)', '2026-06-28T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (61, 'Portugal', 'Congo DR', 'Grupo K', 'Houston', '2026-06-17T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (62, 'Uzbekistan', 'Colombia', 'Grupo K', 'Mexico City', '2026-06-18T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (63, 'Portugal', 'Uzbekistan', 'Grupo K', 'Houston', '2026-06-23T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (64, 'Colombia', 'Congo DR', 'Grupo K', 'Guadalajara (Zapopan)', '2026-06-24T02:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (65, 'Colombia', 'Portugal', 'Grupo K', 'Miami (Miami Gardens)', '2026-06-27T23:30:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (66, 'Congo DR', 'Uzbekistan', 'Grupo K', 'Atlanta', '2026-06-27T23:30:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (67, 'England', 'Croatia', 'Grupo L', 'Dallas (Arlington)', '2026-06-17T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (68, 'Ghana', 'Panama', 'Grupo L', 'Toronto', '2026-06-17T23:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (69, 'England', 'Ghana', 'Grupo L', 'Boston (Foxborough)', '2026-06-23T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (70, 'Panama', 'Croatia', 'Grupo L', 'Toronto', '2026-06-23T23:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (71, 'Panama', 'England', 'Grupo L', 'New York/New Jersey (East Rutherford)', '2026-06-27T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (72, 'Croatia', 'Ghana', 'Grupo L', 'Philadelphia', '2026-06-27T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (73, '2A', '2B', 'Round of 32', 'Los Angeles (Inglewood)', '2026-06-28T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (74, '1E', '3A/B/C/D/F', 'Round of 32', 'Boston (Foxborough)', '2026-06-29T20:30:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (75, '1F', '2C', 'Round of 32', 'Monterrey (Guadalupe)', '2026-06-30T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (76, '1C', '2F', 'Round of 32', 'Houston', '2026-06-29T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (77, '1I', '3C/D/F/G/H', 'Round of 32', 'New York/New Jersey (East Rutherford)', '2026-06-30T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (78, '2E', '2I', 'Round of 32', 'Dallas (Arlington)', '2026-06-30T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (79, '1A', '3C/E/F/H/I', 'Round of 32', 'Mexico City', '2026-07-01T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (80, '1L', '3E/H/I/J/K', 'Round of 32', 'Atlanta', '2026-07-01T16:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (81, '1D', '3B/E/F/I/J', 'Round of 32', 'San Francisco Bay Area (Santa Clara)', '2026-07-02T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (82, '1G', '3A/E/H/I/J', 'Round of 32', 'Seattle', '2026-07-01T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (83, '2K', '2L', 'Round of 32', 'Toronto', '2026-07-02T23:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (84, '1H', '2J', 'Round of 32', 'Los Angeles (Inglewood)', '2026-07-02T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (85, '1B', '3E/F/G/I/J', 'Round of 32', 'Vancouver', '2026-07-03T03:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (86, '1J', '2H', 'Round of 32', 'Miami (Miami Gardens)', '2026-07-03T22:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (87, '1K', '3D/E/I/J/L', 'Round of 32', 'Kansas City', '2026-07-04T01:30:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (88, '2D', '2G', 'Round of 32', 'Dallas (Arlington)', '2026-07-03T18:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (89, 'W74', 'W77', 'Round of 16', 'Philadelphia', '2026-07-04T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (90, 'W73', 'W75', 'Round of 16', 'Houston', '2026-07-04T17:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (91, 'W76', 'W78', 'Round of 16', 'New York/New Jersey (East Rutherford)', '2026-07-05T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (92, 'W79', 'W80', 'Round of 16', 'Mexico City', '2026-07-06T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (93, 'W83', 'W84', 'Round of 16', 'Dallas (Arlington)', '2026-07-06T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (94, 'W81', 'W82', 'Round of 16', 'Seattle', '2026-07-07T00:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (95, 'W86', 'W88', 'Round of 16', 'Atlanta', '2026-07-07T16:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (96, 'W85', 'W87', 'Round of 16', 'Vancouver', '2026-07-07T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (97, 'W89', 'W90', 'Quarter-final', 'Boston (Foxborough)', '2026-07-09T20:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (98, 'W93', 'W94', 'Quarter-final', 'Los Angeles (Inglewood)', '2026-07-10T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (99, 'W91', 'W92', 'Quarter-final', 'Miami (Miami Gardens)', '2026-07-11T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (100, 'W95', 'W96', 'Quarter-final', 'Kansas City', '2026-07-12T01:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (101, 'W97', 'W98', 'Semi-final', 'Dallas (Arlington)', '2026-07-14T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (102, 'W99', 'W100', 'Semi-final', 'Atlanta', '2026-07-15T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (103, 'L101', 'L102', 'Match for third place', 'Miami (Miami Gardens)', '2026-07-18T21:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;
INSERT INTO public.matches (id, home_team, away_team, stage_group, venue, match_date, status) VALUES (104, 'W101', 'W102', 'Final', 'New York/New Jersey (East Rutherford)', '2026-07-19T19:00:00Z', 'pending') ON CONFLICT (id) DO UPDATE SET home_team = EXCLUDED.home_team, away_team = EXCLUDED.away_team, stage_group = EXCLUDED.stage_group, venue = EXCLUDED.venue, match_date = EXCLUDED.match_date;

-- Reset matches identity sequence to avoid duplicate key errors on future inserts
SELECT setval(pg_get_serial_sequence('public.matches', 'id'), COALESCE(MAX(id), 1)) FROM public.matches;


-- ==========================================
-- WORLD CUP EMULATION & PHASE LEADERBOARD
-- ==========================================

-- Function to emulate the entire World Cup phase by phase
CREATE OR REPLACE FUNCTION public.emulate_world_cup()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  m_id int;
  p_home int;
  p_away int;
  res text;
BEGIN
  -- Validate that requester is admin
  IF auth.jwt() ->> 'email' != 'admin@quiniela.local' THEN
    RAISE EXCEPTION 'Acceso denegado. Solo administradores.';
  END IF;

  -- 1. Reset all matches status and scores
  UPDATE public.matches
  SET home_score = null,
      away_score = null,
      status = 'pending'
  WHERE id IS NOT NULL;

  -- 2. Restore original teams for matches 73 to 104
  UPDATE public.matches SET home_team = '2º Grupo A', away_team = '2º Grupo B' WHERE id = 73;
  UPDATE public.matches SET home_team = '1º Grupo E', away_team = '3º Grupo A/B/C/D/F' WHERE id = 74;
  UPDATE public.matches SET home_team = '1º Grupo F', away_team = '2º Grupo C' WHERE id = 75;
  UPDATE public.matches SET home_team = '1º Grupo C', away_team = '2º Grupo F' WHERE id = 76;
  UPDATE public.matches SET home_team = '1º Grupo I', away_team = '3º Grupo C/D/F/G/H' WHERE id = 77;
  UPDATE public.matches SET home_team = '2º Grupo E', away_team = '2º Grupo I' WHERE id = 78;
  UPDATE public.matches SET home_team = '1º Grupo A', away_team = '3º Grupo C/E/F/H/I' WHERE id = 79;
  UPDATE public.matches SET home_team = '1º Grupo L', away_team = '3º Grupo E/H/I/J/K' WHERE id = 80;
  UPDATE public.matches SET home_team = '1º Grupo D', away_team = '3º Grupo B/E/F/I/J' WHERE id = 81;
  UPDATE public.matches SET home_team = '1º Grupo G', away_team = '3º Grupo A/E/H/I/J' WHERE id = 82;
  UPDATE public.matches SET home_team = '2º Grupo K', away_team = '2º Grupo L' WHERE id = 83;
  UPDATE public.matches SET home_team = '1º Grupo H', away_team = '2º Grupo J' WHERE id = 84;
  UPDATE public.matches SET home_team = '1º Grupo B', away_team = '3º Grupo E/F/G/I/J' WHERE id = 85;
  UPDATE public.matches SET home_team = '1º Grupo J', away_team = '2º Grupo H' WHERE id = 86;
  UPDATE public.matches SET home_team = '1º Grupo K', away_team = '3º Grupo D/E/I/J/L' WHERE id = 87;
  UPDATE public.matches SET home_team = '2º Grupo D', away_team = '2º Grupo G' WHERE id = 88;
  UPDATE public.matches SET home_team = 'Ganador Partido 74', away_team = 'Ganador Partido 77' WHERE id = 89;
  UPDATE public.matches SET home_team = 'Ganador Partido 73', away_team = 'Ganador Partido 75' WHERE id = 90;
  UPDATE public.matches SET home_team = 'Ganador Partido 76', away_team = 'Ganador Partido 78' WHERE id = 91;
  UPDATE public.matches SET home_team = 'Ganador Partido 79', away_team = 'Ganador Partido 80' WHERE id = 92;
  UPDATE public.matches SET home_team = 'Ganador Partido 83', away_team = 'Ganador Partido 84' WHERE id = 93;
  UPDATE public.matches SET home_team = 'Ganador Partido 81', away_team = 'Ganador Partido 82' WHERE id = 94;
  UPDATE public.matches SET home_team = 'Ganador Partido 86', away_team = 'Ganador Partido 88' WHERE id = 95;
  UPDATE public.matches SET home_team = 'Ganador Partido 85', away_team = 'Ganador Partido 87' WHERE id = 96;
  UPDATE public.matches SET home_team = 'Ganador Partido 89', away_team = 'Ganador Partido 90' WHERE id = 97;
  UPDATE public.matches SET home_team = 'Ganador Partido 93', away_team = 'Ganador Partido 94' WHERE id = 98;
  UPDATE public.matches SET home_team = 'Ganador Partido 91', away_team = 'Ganador Partido 92' WHERE id = 99;
  UPDATE public.matches SET home_team = 'Ganador Partido 95', away_team = 'Ganador Partido 96' WHERE id = 100;
  UPDATE public.matches SET home_team = 'Ganador Partido 97', away_team = 'Ganador Partido 98' WHERE id = 101;
  UPDATE public.matches SET home_team = 'Ganador Partido 99', away_team = 'Ganador Partido 100' WHERE id = 102;
  UPDATE public.matches SET home_team = 'Perdedor Partido 101', away_team = 'Perdedor Partido 102' WHERE id = 103;
  UPDATE public.matches SET home_team = 'Ganador Partido 101', away_team = 'Ganador Partido 102' WHERE id = 104;

  -- 3. Seed dummy users and predictions
  res := public.seed_dummies_and_predictions();

  -- 4. Emulate Phase 1: Group Stage (matches 1..72)
  FOR m_id IN 1..72 LOOP
    p_home := floor(random() * 5);
    p_away := floor(random() * 5);
    UPDATE public.matches
    SET home_score = p_home,
        away_score = p_away,
        status = 'finished'
    WHERE id = m_id;
  END LOOP;

  -- 5. Emulate Phase 2: Round of 32 (matches 73..88)
  FOR m_id IN 73..88 LOOP
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    IF p_home = p_away THEN
      p_home := p_home + 1;
    END IF;
    UPDATE public.matches
    SET home_score = p_home,
        away_score = p_away,
        status = 'finished'
    WHERE id = m_id;
  END LOOP;

  -- 6. Emulate Phase 3: Round of 16 (matches 89..96)
  FOR m_id IN 89..96 LOOP
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    IF p_home = p_away THEN
      p_home := p_home + 1;
    END IF;
    UPDATE public.matches
    SET home_score = p_home,
        away_score = p_away,
        status = 'finished'
    WHERE id = m_id;
  END LOOP;

  -- 7. Emulate Phase 4: Quarterfinals (matches 97..100)
  FOR m_id IN 97..100 LOOP
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    IF p_home = p_away THEN
      p_home := p_home + 1;
    END IF;
    UPDATE public.matches
    SET home_score = p_home,
        away_score = p_away,
        status = 'finished'
    WHERE id = m_id;
  END LOOP;

  -- 8. Emulate Phase 5: Semifinals (matches 101..102)
  FOR m_id IN 101..102 LOOP
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    IF p_home = p_away THEN
      p_home := p_home + 1;
    END IF;
    UPDATE public.matches
    SET home_score = p_home,
        away_score = p_away,
        status = 'finished'
    WHERE id = m_id;
  END LOOP;

  -- 9. Emulate Phase 6: Third Place and Final (matches 103..104)
  FOR m_id IN 103..104 LOOP
    p_home := floor(random() * 4);
    p_away := floor(random() * 4);
    IF p_home = p_away THEN
      p_home := p_home + 1;
    END IF;
    UPDATE public.matches
    SET home_score = p_home,
        away_score = p_away,
        status = 'finished'
    WHERE id = m_id;
  END LOOP;

  RETURN '¡Emulación completa del Mundial finalizada con éxito! Todos los partidos han sido jugados y los puntos de las predicciones de los 5 usuarios dummy calculados.';
END;
$$;

-- Function to compute leaderboard by phase
CREATE OR REPLACE FUNCTION public.get_leaderboard_by_phase()
RETURNS table(
  username text,
  fase1 bigint,
  fase2 bigint,
  fase3 bigint,
  fase4 bigint,
  fase5 bigint,
  fase6 bigint,
  total_points bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    split_part(u.email, '@', 1)::text as username,
    (coalesce(sum(CASE WHEN p.match_id >= 1 AND p.match_id <= 72 THEN p.points ELSE 0 END), 0) + coalesce(t.fase1_trivia, 0))::bigint as fase1,
    (coalesce(sum(CASE WHEN p.match_id >= 73 AND p.match_id <= 88 THEN p.points ELSE 0 END), 0) + coalesce(t.fase2_trivia, 0))::bigint as fase2,
    (coalesce(sum(CASE WHEN p.match_id >= 89 AND p.match_id <= 96 THEN p.points ELSE 0 END), 0) + coalesce(t.fase3_trivia, 0))::bigint as fase3,
    (coalesce(sum(CASE WHEN p.match_id >= 97 AND p.match_id <= 100 THEN p.points ELSE 0 END), 0) + coalesce(t.fase4_trivia, 0))::bigint as fase4,
    (coalesce(sum(CASE WHEN p.match_id >= 101 AND p.match_id <= 102 THEN p.points ELSE 0 END), 0) + coalesce(t.fase5_trivia, 0))::bigint as fase5,
    (coalesce(sum(CASE WHEN p.match_id >= 103 AND p.match_id <= 104 THEN p.points ELSE 0 END), 0) + coalesce(t.fase6_trivia, 0))::bigint as fase6,
    (coalesce(sum(p.points), 0) + coalesce(t.total_trivia, 0))::bigint as total_points
  FROM auth.users u
  LEFT JOIN public.predictions p ON u.id = p.user_id
  LEFT JOIN (
    SELECT
      ta.user_id,
      coalesce(sum(CASE WHEN tq.trivia_date <= '2026-06-27' THEN ta.points ELSE 0 END), 0)::bigint as fase1_trivia,
      coalesce(sum(CASE WHEN tq.trivia_date >= '2026-06-28' AND tq.trivia_date <= '2026-07-03' THEN ta.points ELSE 0 END), 0)::bigint as fase2_trivia,
      coalesce(sum(CASE WHEN tq.trivia_date >= '2026-07-04' AND tq.trivia_date <= '2026-07-07' THEN ta.points ELSE 0 END), 0)::bigint as fase3_trivia,
      coalesce(sum(CASE WHEN tq.trivia_date >= '2026-07-08' AND tq.trivia_date <= '2026-07-12' THEN ta.points ELSE 0 END), 0)::bigint as fase4_trivia,
      coalesce(sum(CASE WHEN tq.trivia_date >= '2026-07-13' AND tq.trivia_date <= '2026-07-15' THEN ta.points ELSE 0 END), 0)::bigint as fase5_trivia,
      coalesce(sum(CASE WHEN tq.trivia_date >= '2026-07-16' THEN ta.points ELSE 0 END), 0)::bigint as fase6_trivia,
      coalesce(sum(ta.points), 0)::bigint as total_trivia
    FROM public.trivia_answers ta
    INNER JOIN public.trivia_questions tq ON ta.question_id = tq.id
    GROUP BY ta.user_id
  ) t ON u.id = t.user_id
  WHERE u.email LIKE '%@quiniela.local' AND u.email != 'admin@quiniela.local'
  GROUP BY u.email, t.fase1_trivia, t.fase2_trivia, t.fase3_trivia, t.fase4_trivia, t.fase5_trivia, t.fase6_trivia, t.total_trivia
  ORDER BY total_points DESC, username ASC;
END;
$$;
