-- ==========================================
-- TRIVIA DIARIA — Migration
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Trivia Questions Table
create table if not exists public.trivia_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  options jsonb not null,          -- ["opcion1","opcion2","opcion3","opcion4"]
  correct_index int not null,      -- 0-based index into options array
  trivia_date date not null unique, -- the day this question is active
  category text not null default 'general',
  created_at timestamptz not null default now()
);

-- 2. Trivia Answers Table
create table if not exists public.trivia_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.trivia_questions(id) on delete cascade,
  selected_index int not null,
  is_correct boolean not null default false,
  points int not null default 0,
  answered_at timestamptz not null default now()
);

-- One answer per user per question
create unique index if not exists trivia_answers_user_question_unique
  on public.trivia_answers (user_id, question_id);

-- Enable RLS
alter table public.trivia_questions enable row level security;
alter table public.trivia_answers enable row level security;

-- ==========================================
-- RLS Policies — trivia_questions
-- ==========================================

-- Everyone can read questions
drop policy if exists trivia_questions_select_public on public.trivia_questions;
create policy trivia_questions_select_public on public.trivia_questions
  for select using (true);

-- Only admin can insert/update/delete
drop policy if exists trivia_questions_insert_admin on public.trivia_questions;
create policy trivia_questions_insert_admin on public.trivia_questions
  for insert with check (auth.jwt() ->> 'email' = 'admin@quiniela.local');

drop policy if exists trivia_questions_update_admin on public.trivia_questions;
create policy trivia_questions_update_admin on public.trivia_questions
  for update using (auth.jwt() ->> 'email' = 'admin@quiniela.local')
  with check (auth.jwt() ->> 'email' = 'admin@quiniela.local');

drop policy if exists trivia_questions_delete_admin on public.trivia_questions;
create policy trivia_questions_delete_admin on public.trivia_questions
  for delete using (auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- ==========================================
-- RLS Policies — trivia_answers
-- ==========================================

-- Users can read their own answers
drop policy if exists trivia_answers_select_own on public.trivia_answers;
create policy trivia_answers_select_own on public.trivia_answers
  for select using (auth.uid() = user_id);

-- Users can insert their own answers
drop policy if exists trivia_answers_insert_own on public.trivia_answers;
create policy trivia_answers_insert_own on public.trivia_answers
  for insert with check (auth.uid() = user_id);

-- Admin can read all answers (for stats)
drop policy if exists trivia_answers_select_admin on public.trivia_answers;
create policy trivia_answers_select_admin on public.trivia_answers
  for select using (auth.jwt() ->> 'email' = 'admin@quiniela.local');

-- ==========================================
-- RPC: get_today_trivia
-- Returns today's question. If the user already answered, includes their answer.
-- Never exposes correct_index before the user has answered.
-- ==========================================
create or replace function public.get_today_trivia()
returns jsonb
language plpgsql
security definer
as $$
declare
  q_record record;
  a_record record;
  result jsonb;
begin
  -- Get today's question (Costa Rica timezone = UTC-6)
  select * into q_record
  from public.trivia_questions
  where trivia_date = (now() at time zone 'America/Costa_Rica')::date;

  if q_record is null then
    return jsonb_build_object('status', 'no_question');
  end if;

  -- Check if the current user already answered
  select * into a_record
  from public.trivia_answers
  where user_id = auth.uid()
    and question_id = q_record.id;

  if a_record is not null then
    -- Already answered: include correct_index so UI can show result
    result := jsonb_build_object(
      'status', 'answered',
      'question_id', q_record.id,
      'question', q_record.question,
      'options', q_record.options,
      'category', q_record.category,
      'correct_index', q_record.correct_index,
      'selected_index', a_record.selected_index,
      'is_correct', a_record.is_correct,
      'points', a_record.points
    );
  else
    -- Not answered yet: hide the correct answer
    result := jsonb_build_object(
      'status', 'unanswered',
      'question_id', q_record.id,
      'question', q_record.question,
      'options', q_record.options,
      'category', q_record.category
    );
  end if;

  return result;
end;
$$;

-- ==========================================
-- RPC: submit_trivia_answer
-- Validates, scores (2 pts for correct), prevents double-submit.
-- ==========================================
create or replace function public.submit_trivia_answer(
  p_question_id bigint,
  p_selected_index int
)
returns jsonb
language plpgsql
security definer
as $$
declare
  q_record record;
  correct boolean;
  pts int;
  existing_id bigint;
begin
  -- Verify the question exists and is today's question
  select * into q_record
  from public.trivia_questions
  where id = p_question_id
    and trivia_date = (now() at time zone 'America/Costa_Rica')::date;

  if q_record is null then
    return jsonb_build_object('error', 'Pregunta no válida o no es la del día de hoy.');
  end if;

  -- Check if already answered
  select id into existing_id
  from public.trivia_answers
  where user_id = auth.uid()
    and question_id = p_question_id;

  if existing_id is not null then
    return jsonb_build_object('error', 'Ya respondiste esta pregunta.');
  end if;

  -- Validate selected_index
  if p_selected_index < 0 or p_selected_index >= jsonb_array_length(q_record.options) then
    return jsonb_build_object('error', 'Opción no válida.');
  end if;

  -- Score it
  correct := (p_selected_index = q_record.correct_index);
  pts := case when correct then 2 else 0 end;

  -- Insert answer
  insert into public.trivia_answers (user_id, question_id, selected_index, is_correct, points)
  values (auth.uid(), p_question_id, p_selected_index, correct, pts);

  return jsonb_build_object(
    'status', 'ok',
    'is_correct', correct,
    'correct_index', q_record.correct_index,
    'points', pts
  );
end;
$$;

-- ==========================================
-- RPC: get_trivia_stats
-- Returns trivia stats for the current user.
-- ==========================================
create or replace function public.get_trivia_stats()
returns jsonb
language plpgsql
security definer
as $$
declare
  total_answered int;
  total_correct int;
  total_pts bigint;
  current_streak int;
  a_rec record;
begin
  select
    count(*)::int,
    count(*) filter (where is_correct)::int,
    coalesce(sum(points), 0)::bigint
  into total_answered, total_correct, total_pts
  from public.trivia_answers
  where user_id = auth.uid();

  -- Calculate current streak (consecutive correct answers, most recent first)
  current_streak := 0;
  for a_rec in
    select ta.is_correct
    from public.trivia_answers ta
    inner join public.trivia_questions tq on tq.id = ta.question_id
    where ta.user_id = auth.uid()
    order by tq.trivia_date desc
  loop
    if a_rec.is_correct then
      current_streak := current_streak + 1;
    else
      exit;
    end if;
  end loop;

  return jsonb_build_object(
    'total_answered', total_answered,
    'total_correct', total_correct,
    'total_points', total_pts,
    'current_streak', current_streak
  );
end;
$$;

-- ==========================================
-- UPDATE: get_leaderboard to include trivia points
-- ==========================================
create or replace function public.get_leaderboard()
returns table(username text, total_points bigint, predictions_count bigint)
language plpgsql
security definer
as $$
declare
  curr_phase int;
begin
  -- Determine current active phase based on first pending match
  select 
    case 
      when min(id) is null then 6
      when min(id) <= 72 then 1
      when min(id) <= 88 then 2
      when min(id) <= 96 then 3
      when min(id) <= 100 then 4
      when min(id) <= 102 then 5
      else 6
    end into curr_phase
  from public.matches
  where status != 'finished';

  if curr_phase is null then
    curr_phase := 6;
  end if;

  return query
  select
    split_part(u.email, '@', 1)::text as username,
    (
      coalesce(sum(case 
        when curr_phase = 1 and p.match_id >= 1 and p.match_id <= 72 then p.points
        when curr_phase = 2 and p.match_id >= 73 and p.match_id <= 88 then p.points
        when curr_phase = 3 and p.match_id >= 89 and p.match_id <= 96 then p.points
        when curr_phase = 4 and p.match_id >= 97 and p.match_id <= 100 then p.points
        when curr_phase = 5 and p.match_id >= 101 and p.match_id <= 102 then p.points
        when curr_phase = 6 and p.match_id >= 103 and p.match_id <= 104 then p.points
        else 0
      end), 0) + coalesce(t.trivia_pts, 0)
    )::bigint as total_points,
    sum(case 
      when curr_phase = 1 and p.match_id >= 1 and p.match_id <= 72 then 1
      when curr_phase = 2 and p.match_id >= 73 and p.match_id <= 88 then 1
      when curr_phase = 3 and p.match_id >= 89 and p.match_id <= 96 then 1
      when curr_phase = 4 and p.match_id >= 97 and p.match_id <= 100 then 1
      when curr_phase = 5 and p.match_id >= 101 and p.match_id <= 102 then 1
      when curr_phase = 6 and p.match_id >= 103 and p.match_id <= 104 then 1
      else 0
    end)::bigint as predictions_count
  from auth.users u
  left join public.predictions p on u.id = p.user_id
  left join (
    select 
      ta.user_id,
      sum(ta.points)::bigint as trivia_pts
    from public.trivia_answers ta
    inner join public.trivia_questions tq on ta.question_id = tq.id
    where 
      (curr_phase = 1 and tq.trivia_date <= '2026-06-27') or
      (curr_phase = 2 and tq.trivia_date >= '2026-06-28' and tq.trivia_date <= '2026-07-03') or
      (curr_phase = 3 and tq.trivia_date >= '2026-07-04' and tq.trivia_date <= '2026-07-07') or
      (curr_phase = 4 and tq.trivia_date >= '2026-07-08' and tq.trivia_date <= '2026-07-12') or
      (curr_phase = 5 and tq.trivia_date >= '2026-07-13' and tq.trivia_date <= '2026-07-15') or
      (curr_phase = 6 and tq.trivia_date >= '2026-07-16')
    group by ta.user_id
  ) t on u.id = t.user_id
  where u.email like '%@quiniela.local' and u.email != 'admin@quiniela.local'
  group by u.email, t.trivia_pts
  order by total_points desc, predictions_count desc, username asc;
end;
$$;

-- ==========================================
-- UPDATE: get_leaderboard_by_phase to include trivia points
-- ==========================================
create or replace function public.get_leaderboard_by_phase()
returns table(
  username text,
  fase1 bigint,
  fase2 bigint,
  fase3 bigint,
  fase4 bigint,
  fase5 bigint,
  fase6 bigint,
  total_points bigint
)
language plpgsql
security definer
as $$
begin
  return query
  select
    split_part(u.email, '@', 1)::text as username,
    (coalesce(sum(case when p.match_id >= 1 and p.match_id <= 72 then p.points else 0 end), 0) + coalesce(t.fase1_trivia, 0))::bigint as fase1,
    (coalesce(sum(case when p.match_id >= 73 and p.match_id <= 88 then p.points else 0 end), 0) + coalesce(t.fase2_trivia, 0))::bigint as fase2,
    (coalesce(sum(case when p.match_id >= 89 and p.match_id <= 96 then p.points else 0 end), 0) + coalesce(t.fase3_trivia, 0))::bigint as fase3,
    (coalesce(sum(case when p.match_id >= 97 and p.match_id <= 100 then p.points else 0 end), 0) + coalesce(t.fase4_trivia, 0))::bigint as fase4,
    (coalesce(sum(case when p.match_id >= 101 and p.match_id <= 102 then p.points else 0 end), 0) + coalesce(t.fase5_trivia, 0))::bigint as fase5,
    (coalesce(sum(case when p.match_id >= 103 and p.match_id <= 104 then p.points else 0 end), 0) + coalesce(t.fase6_trivia, 0))::bigint as fase6,
    (coalesce(sum(p.points), 0) + coalesce(t.total_trivia, 0))::bigint as total_points
  from auth.users u
  left join public.predictions p on u.id = p.user_id
  left join (
    select
      ta.user_id,
      coalesce(sum(case when tq.trivia_date <= '2026-06-27' then ta.points else 0 end), 0)::bigint as fase1_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-06-28' and tq.trivia_date <= '2026-07-03' then ta.points else 0 end), 0)::bigint as fase2_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-04' and tq.trivia_date <= '2026-07-07' then ta.points else 0 end), 0)::bigint as fase3_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-08' and tq.trivia_date <= '2026-07-12' then ta.points else 0 end), 0)::bigint as fase4_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-13' and tq.trivia_date <= '2026-07-15' then ta.points else 0 end), 0)::bigint as fase5_trivia,
      coalesce(sum(case when tq.trivia_date >= '2026-07-16' then ta.points else 0 end), 0)::bigint as fase6_trivia,
      coalesce(sum(ta.points), 0)::bigint as total_trivia
    from public.trivia_answers ta
    inner join public.trivia_questions tq on ta.question_id = tq.id
    group by ta.user_id
  ) t on u.id = t.user_id
  where u.email like '%@quiniela.local' and u.email != 'admin@quiniela.local'
  group by u.email, t.fase1_trivia, t.fase2_trivia, t.fase3_trivia, t.fase4_trivia, t.fase5_trivia, t.fase6_trivia, t.total_trivia
  order by total_points desc, username asc;
end;
$$;

-- ==========================================
-- SEED: 30 trivia questions (June 11 - July 10, 2026)
-- ==========================================
insert into public.trivia_questions (question, options, correct_index, trivia_date, category) values
  ('¿Qué país ganó la primera Copa del Mundo en 1930?',
   '["Brasil", "Uruguay", "Argentina", "Italia"]', 1, '2026-06-11', 'historia'),

  ('¿Cuántos equipos participarán en el Mundial 2026?',
   '["32", "36", "48", "64"]', 2, '2026-06-12', '2026'),

  ('¿Quién es el máximo goleador en la historia de los Mundiales?',
   '["Pelé", "Ronaldo", "Miroslav Klose", "Gerd Müller"]', 2, '2026-06-13', 'récords'),

  ('¿En qué estadio se jugará la final del Mundial 2026?',
   '["Estadio Azteca", "MetLife Stadium", "SoFi Stadium", "Rose Bowl"]', 1, '2026-06-14', 'sedes'),

  ('¿Qué selección ha ganado más Copas del Mundo?',
   '["Alemania", "Italia", "Brasil", "Argentina"]', 2, '2026-06-15', 'historia'),

  ('¿En qué año se usó el VAR por primera vez en un Mundial?',
   '["2014", "2018", "2022", "2010"]', 1, '2026-06-16', 'reglas'),

  ('¿Qué jugador ha disputado más partidos en Mundiales?',
   '["Lothar Matthäus", "Paolo Maldini", "Lionel Messi", "Cristiano Ronaldo"]', 2, '2026-06-17', 'récords'),

  ('¿Cuántos países serán sede del Mundial 2026?',
   '["1", "2", "3", "4"]', 2, '2026-06-18', '2026'),

  ('¿Qué selección ganó la Copa del Mundo 2022 en Qatar?',
   '["Francia", "Brasil", "Argentina", "Croacia"]', 2, '2026-06-19', 'historia'),

  ('¿Cuál fue el primer Mundial donde se utilizó el balón oficial Adidas?',
   '["1966", "1970", "1974", "1978"]', 1, '2026-06-20', 'historia'),

  ('¿Qué jugador anotó el gol más rápido en la historia de los Mundiales?',
   '["Hakan Şükür", "Clint Dempsey", "Neymar", "Thomas Müller"]', 0, '2026-06-21', 'récords'),

  ('¿Qué ciudad mexicana será sede en el Mundial 2026?',
   '["Guadalajara", "Monterrey", "Ciudad de México", "Cancún"]', 2, '2026-06-22', 'sedes'),

  ('¿Cuántos partidos se jugarán en total en el Mundial 2026?',
   '["64", "80", "104", "96"]', 2, '2026-06-23', '2026'),

  ('¿Qué selección fue eliminada en fase de grupos en el Mundial 2022 siendo la vigente campeona?',
   '["Francia", "Alemania", "España", "Ninguna fue eliminada"]', 1, '2026-06-24', 'historia'),

  ('¿Qué portero ha mantenido más veces la portería a cero en Mundiales?',
   '["Manuel Neuer", "Gianluigi Buffon", "Fabien Barthez", "Peter Shilton"]', 2, '2026-06-25', 'récords'),

  ('¿Cuál es el país más pequeño en clasificar a un Mundial?',
   '["Islandia", "Trinidad y Tobago", "Curazao", "Panamá"]', 0, '2026-06-26', 'historia'),

  ('¿Qué jugador tiene más asistencias en la historia de los Mundiales?',
   '["Diego Maradona", "Pelé", "Lionel Messi", "David Beckham"]', 2, '2026-06-27', 'récords'),

  ('¿En qué año se introdujo la tanda de penales en los Mundiales?',
   '["1970", "1978", "1982", "1986"]', 1, '2026-06-28', 'reglas'),

  ('¿Qué selección nunca ha perdido una final de Copa del Mundo?',
   '["Brasil", "Argentina", "Uruguay", "España"]', 2, '2026-06-29', 'historia'),

  ('¿Cuántas ciudades de EE.UU. serán sede del Mundial 2026?',
   '["8", "11", "14", "16"]', 1, '2026-06-30', 'sedes'),

  ('¿Quién anotó el "Gol del Siglo" en México 86?',
   '["Pelé", "Diego Maradona", "Zinedine Zidane", "Johan Cruyff"]', 1, '2026-07-01', 'historia'),

  ('¿Qué selección recibió la primera tarjeta roja en la historia de los Mundiales?',
   '["Chile", "Argentina", "Italia", "Uruguay"]', 0, '2026-07-02', 'reglas'),

  ('¿Cuál es el resultado más abultado en la historia de los Mundiales?',
   '["Alemania 7-1 Brasil", "Hungría 10-1 El Salvador", "Australia 31-0 Samoa", "Yugoslavia 9-0 Zaire"]', 1, '2026-07-03', 'récords'),

  ('¿En qué país se celebró el primer Mundial con 32 equipos?',
   '["Japón/Corea", "Francia", "Estados Unidos", "Sudáfrica"]', 1, '2026-07-04', 'historia'),

  ('¿Qué selección ha sido eliminada más veces en penales en Mundiales?',
   '["Inglaterra", "España", "Italia", "Argentina"]', 0, '2026-07-05', 'récords'),

  ('¿Cuántos grupos habrá en el Mundial 2026?',
   '["8", "10", "12", "16"]', 2, '2026-07-06', '2026'),

  ('¿Qué jugador marcó un hat-trick en la final del Mundial 2022?',
   '["Lionel Messi", "Kylian Mbappé", "Olivier Giroud", "Julián Álvarez"]', 1, '2026-07-07', 'historia'),

  ('¿Cuál es la mascota oficial del Mundial 2026?',
   '["Ike", "Zabivaka", "Fuleco", "La''eeb"]', 0, '2026-07-08', '2026'),

  ('¿Qué país centroamericano clasificó por primera vez a un Mundial en 2018?',
   '["Costa Rica", "Honduras", "Panamá", "El Salvador"]', 2, '2026-07-09', 'historia'),

  ('¿Cuántas veces ha sido campeón del mundo Alemania?',
   '["3", "4", "5", "6"]', 1, '2026-07-10', 'historia')

on conflict (trivia_date) do nothing;
